FEATURE_REGISTRY = [
    # --- DASHBOARD ---
    {
        "key": "nav_dashboard",
        "label": "Dashboard",
        "category": "NAVIGATION",
        "description": "Main platform overview and analytics dashboard",
        "is_parent": False,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 10,
    },

    # --- REPORT GENERATOR (PARENT) ---
    {
        "key": "nav_report_generator",
        "label": "Report Generator",
        "category": "REPORTS",
        "description": "Daily recitation report builder, sessions, comment templates, and history archive",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 12,
    },
    {
        "key": "report_builder",
        "label": "Daily Report Builder",
        "category": "REPORTS",
        "description": "Hifz recitation tracker, error logging, and live WhatsApp/PDF report generator",
        "is_parent": False,
        "parent_key": "nav_report_generator",
        "default_enabled": True,
        "sort_order": 13,
    },
    {
        "key": "report_sessions_comments",
        "label": "Sessions & Comment Templates",
        "category": "REPORTS",
        "description": "Custom recitation sessions and preset feedback comment templates",
        "is_parent": False,
        "parent_key": "nav_report_generator",
        "default_enabled": True,
        "sort_order": 14,
    },
    {
        "key": "report_history",
        "label": "Report History & Records",
        "category": "REPORTS",
        "description": "Student daily recitation history, analytics, and record logs",
        "is_parent": False,
        "parent_key": "nav_report_generator",
        "default_enabled": True,
        "sort_order": 15,
    },
    {
        "key": "report_copy_settings",
        "label": "Copy Report Settings",
        "category": "REPORTS",
        "description": "Formatting preferences for generated report text and preview options",
        "is_parent": False,
        "parent_key": "nav_report_generator",
        "default_enabled": True,
        "sort_order": 16,
    },

    # --- ACADEMIC INSTITUTION (PARENT) ---
    {
        "key": "nav_institution",
        "label": "Academic Institution",
        "category": "INSTITUTIONS",
        "description": "Enterprise multi-tenant institution directory, branding, and academic hierarchy",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 15,
    },
    {
        "key": "app_institutions",
        "label": "Institution Directory",
        "category": "INSTITUTIONS",
        "description": "Multi-tenant academic institutions, hierarchy configurations, and onboarding",
        "is_parent": False,
        "parent_key": "nav_institution",
        "default_enabled": True,
        "sort_order": 16,
    },
    {
        "key": "settings_institution",
        "label": "Profile & Branding",
        "category": "INSTITUTIONS",
        "description": "Institution branding, monogram, campus contacts, and document print presets",
        "is_parent": False,
        "parent_key": "nav_institution",
        "default_enabled": True,
        "sort_order": 17,
    },
    {
        "key": "student_departments",
        "label": "Department Hierarchy",
        "category": "INSTITUTIONS",
        "description": "Configure academic departments, divisional heads, and curriculum tracker presets",
        "is_parent": False,
        "parent_key": "nav_institution",
        "default_enabled": True,
        "sort_order": 18,
    },
    {
        "key": "student_classes",
        "label": "Class Management",
        "category": "INSTITUTIONS",
        "description": "Configure classes, assigned head teachers, and promotion rules",
        "is_parent": False,
        "parent_key": "nav_institution",
        "default_enabled": True,
        "sort_order": 19,
    },
    {
        "key": "student_groups",
        "label": "Group Management",
        "category": "INSTITUTIONS",
        "description": "Sub-sections, seat capacities, and halqa mentors",
        "is_parent": False,
        "parent_key": "nav_institution",
        "default_enabled": True,
        "sort_order": 20,
    },

    # --- STUDENT MANAGEMENT (PARENT) ---
    {
        "key": "nav_student_management",
        "label": "Student Management",
        "category": "STUDENTS",
        "description": "Student admission, rosters, and halqa/group management",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 30,
    },
    {
        "key": "student_roster",
        "label": "Student Roster",
        "category": "STUDENTS",
        "description": "Directory of enrolled students",
        "is_parent": False,
        "parent_key": "nav_student_management",
        "default_enabled": True,
        "sort_order": 31,
    },
    {
        "key": "student_admission",
        "label": "Student Admission",
        "category": "STUDENTS",
        "description": "Quick & full institutional admission wizard",
        "is_parent": False,
        "parent_key": "nav_student_management",
        "default_enabled": True,
        "sort_order": 32,
    },
    {
        "key": "quran_hifz_tracker",
        "label": "Quran Hifz Tracker",
        "category": "STUDENTS",
        "description": "30 Juz interactive visual progress grids and Sabq/Sabqi recitation logs",
        "is_parent": False,
        "parent_key": "nav_student_management",
        "default_enabled": True,
        "sort_order": 33,
    },

    # --- TEACHER & STAFF MANAGEMENT (PARENT) ---
    {
        "key": "nav_staff_management",
        "label": "Staff & Teachers",
        "category": "STAFF",
        "description": "Employee directory, teaching assignments, biometric/web attendance, and leave management",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 35,
    },
    {
        "key": "staff_management",
        "label": "Staff Directory",
        "category": "STAFF",
        "description": "Employee database, designations, teacher/general staff profiles, and onboarding",
        "is_parent": False,
        "parent_key": "nav_staff_management",
        "default_enabled": True,
        "sort_order": 36,
    },
    # --- STUDENT ATTENDANCE (PARENT) ---
    {
        "key": "nav_student_attendance",
        "label": "Student Attendance",
        "category": "ATTENDANCE",
        "description": "Student period-by-period roll call, gate entry tracker, surprise headcount, and 31-day register",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 38,
    },
    {
        "key": "student_attendance",
        "label": "Period & Class Roll Call",
        "category": "ATTENDANCE",
        "description": "Period-wise student roll call, keyboard shortcuts, and live bunk discrepancy alerts",
        "is_parent": False,
        "parent_key": "nav_student_attendance",
        "default_enabled": True,
        "sort_order": 39,
    },
    {
        "key": "student_gate_tracker",
        "label": "Gate Entry & Pass Tracker",
        "category": "ATTENDANCE",
        "description": "Campus gate entry/exit logging, student barcode/RFID scans, and gate pass management",
        "is_parent": False,
        "parent_key": "nav_student_attendance",
        "default_enabled": True,
        "sort_order": 40,
    },
    {
        "key": "student_adhoc_headcount",
        "label": "Surprise Headcount",
        "category": "ATTENDANCE",
        "description": "Night mutala'a, dormitory inspection, and ad-hoc surprise headcount sessions",
        "is_parent": False,
        "parent_key": "nav_student_attendance",
        "default_enabled": True,
        "sort_order": 41,
    },
    {
        "key": "monthly_attendance_matrix",
        "label": "31-Day Student Register",
        "category": "ATTENDANCE",
        "description": "31-day student attendance register matrix grid with rate calculations and export capabilities",
        "is_parent": False,
        "parent_key": "nav_student_attendance",
        "default_enabled": True,
        "sort_order": 42,
    },

    # --- TEACHER & STAFF ATTENDANCE (PARENT) ---
    {
        "key": "nav_staff_attendance",
        "label": "Teacher & Staff Attendance",
        "category": "ATTENDANCE",
        "description": "Teacher period matrix spreadsheet, staff daily timesheets, and leave desk",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 43,
    },
    {
        "key": "teacher_period_matrix",
        "label": "Teacher Period Matrix Register",
        "category": "ATTENDANCE",
        "description": "Spreadsheet-style 31-day teacher period matrix with substitute teacher tagging and dual totals",
        "is_parent": False,
        "parent_key": "nav_staff_attendance",
        "default_enabled": True,
        "sort_order": 44,
    },
    {
        "key": "staff_daily_attendance",
        "label": "Staff Daily Timesheet",
        "category": "ATTENDANCE",
        "description": "Daily employee and general staff timesheet with punch-in/out and work hours",
        "is_parent": False,
        "parent_key": "nav_staff_attendance",
        "default_enabled": True,
        "sort_order": 45,
    },
    {
        "key": "staff_leaves",
        "label": "Leave & Substitution Desk",
        "category": "ATTENDANCE",
        "description": "Staff leave applications, administrative approvals, and substitute teacher assignments",
        "is_parent": False,
        "parent_key": "nav_staff_attendance",
        "default_enabled": True,
        "sort_order": 46,
    },

    # --- ATTENDANCE SETTINGS, CALENDAR & DEVICES (PARENT) ---
    {
        "key": "nav_attendance_management",
        "label": "Attendance Settings & Devices",
        "category": "ATTENDANCE",
        "description": "Dynamic period slots, routine schedules, institutional calendar, and biometric device integration",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 47,
    },
    {
        "key": "attendance_policies_slots",
        "label": "Slots & Routine Manager",
        "category": "ATTENDANCE",
        "description": "Dynamic period slots, teacher routine schedules, weekend selectors, and late arrival policies",
        "is_parent": False,
        "parent_key": "nav_attendance_management",
        "default_enabled": True,
        "sort_order": 48,
    },
    {
        "key": "biometric_device_manager",
        "label": "Biometric Devices",
        "category": "ATTENDANCE",
        "description": "IoT biometric device registry, hardware webhook listeners, and raw punch log processors",
        "is_parent": False,
        "parent_key": "nav_attendance_management",
        "default_enabled": True,
        "sort_order": 49,
    },
    {
        "key": "institutional_calendar",
        "label": "Institutional Calendar",
        "category": "CALENDAR",
        "description": "Multi-tenant academic calendar, holiday/vacation planner, and event schedule",
        "is_parent": False,
        "parent_key": "nav_attendance_management",
        "default_enabled": True,
        "sort_order": 50,
    },
    {
        "key": "institutional_tasks",
        "label": "Institutional Tasks",
        "category": "CALENDAR",
        "description": "Operational task manager, priority checklist, and assignee workflows",
        "is_parent": False,
        "parent_key": "nav_attendance_management",
        "default_enabled": True,
        "sort_order": 51,
    },

    # --- APP MANAGEMENT (PARENT) ---
    {
        "key": "nav_app_management",
        "label": "App Management",
        "category": "ADMIN",
        "description": "Master administrative controls and tools",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 40,
    },
    {
        "key": "app_section_control",
        "label": "Section Control",
        "category": "ADMIN",
        "description": "Enterprise 4-tier feature flag manager",
        "is_parent": False,
        "parent_key": "nav_app_management",
        "default_enabled": True,
        "sort_order": 41,
    },
    {
        "key": "app_user_management",
        "label": "User Management",
        "category": "ADMIN",
        "description": "Global user directories and accounts",
        "is_parent": False,
        "parent_key": "nav_app_management",
        "default_enabled": True,
        "sort_order": 42,
    },
    {
        "key": "app_role_management",
        "label": "Role Management",
        "category": "ADMIN",
        "description": "Custom role creation and permissions",
        "is_parent": False,
        "parent_key": "nav_app_management",
        "default_enabled": True,
        "sort_order": 43,
    },
    {
        "key": "app_activity_analytics",
        "label": "Activity Analytics",
        "category": "ADMIN",
        "description": "User sessions and security log audits",
        "is_parent": False,
        "parent_key": "nav_app_management",
        "default_enabled": True,
        "sort_order": 44,
    },
    {
        "key": "app_role_invites",
        "label": "Role QR & Invite Links",
        "category": "ADMIN",
        "description": "Generate role-based onboarding QR codes and instant join links",
        "is_parent": False,
        "parent_key": "nav_app_management",
        "default_enabled": True,
        "sort_order": 45,
    },

    # --- REPORT GENERATOR (PARENT) ---
    {
        "key": "nav_report_generator",
        "label": "Report Generator",
        "category": "REPORTS",
        "description": "Daily Hifz & academic progress report builder",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 50,
    },
    {
        "key": "report_builder",
        "label": "Generate Report",
        "category": "REPORTS",
        "description": "Hifz daily progress input builder",
        "is_parent": False,
        "parent_key": "nav_report_generator",
        "default_enabled": False,
        "sort_order": 41,
    },
    {
        "key": "report_sessions_comments",
        "label": "Sessions & Comments",
        "category": "REPORTS",
        "description": "Session presets and quick comment library",
        "is_parent": False,
        "parent_key": "nav_report_generator",
        "default_enabled": False,
        "sort_order": 42,
    },
    {
        "key": "report_history",
        "label": "Student Reports History",
        "category": "REPORTS",
        "description": "Historical log of generated progress reports",
        "is_parent": False,
        "parent_key": "nav_report_generator",
        "default_enabled": False,
        "sort_order": 43,
    },
    {
        "key": "report_copy_settings",
        "label": "Copy Report Settings",
        "category": "REPORTS",
        "description": "WhatsApp/Clipboard sharing format customizer",
        "is_parent": False,
        "parent_key": "nav_report_generator",
        "default_enabled": False,
        "sort_order": 44,
    },

    # --- SETTINGS (PARENT) ---
    {
        "key": "nav_settings",
        "label": "Settings",
        "category": "SETTINGS",
        "description": "User preferences and system configuration",
        "is_parent": True,
        "parent_key": None,
        "default_enabled": True,
        "sort_order": 50,
    },
    {
        "key": "settings_profile",
        "label": "Profile Settings",
        "category": "SETTINGS",
        "description": "Account details and avatar customization",
        "is_parent": False,
        "parent_key": "nav_settings",
        "default_enabled": True,
        "sort_order": 51,
    },
    {
        "key": "settings_security",
        "label": "Security & Sessions",
        "category": "SETTINGS",
        "description": "2FA, Passkeys, active sessions, and password management",
        "is_parent": False,
        "parent_key": "nav_settings",
        "default_enabled": False,
        "sort_order": 52,
    },
    {
        "key": "settings_datetime",
        "label": "Date & Time",
        "category": "SETTINGS",
        "description": "Calendar format and timezone preferences",
        "is_parent": False,
        "parent_key": "nav_settings",
        "default_enabled": False,
        "sort_order": 53,
    },
    {
        "key": "settings_appearance",
        "label": "Appearance & Theme",
        "category": "SETTINGS",
        "description": "Dark/Light themes and font scaling",
        "is_parent": False,
        "parent_key": "nav_settings",
        "default_enabled": True,
        "sort_order": 54,
    },
    {
        "key": "settings_language",
        "label": "Language Settings",
        "category": "SETTINGS",
        "description": "Multilingual UI translations",
        "is_parent": False,
        "parent_key": "nav_settings",
        "default_enabled": False,
        "sort_order": 55,
    },
    {
        "key": "settings_backup",
        "label": "Data & Backup",
        "category": "SETTINGS",
        "description": "Export data and local backups",
        "is_parent": False,
        "parent_key": "nav_settings",
        "default_enabled": False,
        "sort_order": 56,
    },

    # --- STANDALONE / AUXILIARY ---
    {
        "key": "nav_trash",
        "label": "Trash & Restoration",
        "category": "SYSTEM",
        "description": "Recycle bin for deleted records",
        "is_parent": False,
        "parent_key": None,
        "default_enabled": False,
        "sort_order": 60,
    },
    {
        "key": "nav_shortcuts",
        "label": "Shortcuts Guide",
        "category": "SYSTEM",
        "description": "Keyboard hotkeys and accessibility reference",
        "is_parent": False,
        "parent_key": None,
        "default_enabled": False,
        "sort_order": 70,
    },
    {
        "key": "nav_app_guide",
        "label": "App Guide & Docs",
        "category": "SYSTEM",
        "description": "Instruction manuals and video tutorials",
        "is_parent": False,
        "parent_key": None,
        "default_enabled": False,
        "sort_order": 80,
    },
    {
        "key": "nav_about",
        "label": "About Platform",
        "category": "SYSTEM",
        "description": "Version information and developer credits",
        "is_parent": False,
        "parent_key": None,
        "default_enabled": False,
        "sort_order": 90,
    },
]
