import { renderAsync } from 'docx-preview';
import mammoth from 'mammoth';

export interface CustomDocxTemplate {
  id: string;
  name: string;
  description?: string;
  rawHtml: string;
  detectedPlaceholders: string[];
  createdAt: string;
  updatedAt: string;
  isTableDocument?: boolean;
  sampleColumns?: Array<{ id: string; header: string; label: string }>;
  sampleData?: Array<Record<string, any>>;
}

export interface DocxParseResult {
  html: string;
  messages: string[];
  detectedPlaceholders: string[];
  isTableDocument: boolean;
  extractedColumns: Array<{ id: string; header: string; label: string }>;
  extractedRows: Array<Record<string, any>>;
}

const TEMPLATES_STORAGE_KEY = 'spr_custom_docx_templates';

/**
 * Parses a Word document (.docx) ArrayBuffer into 100% exact OpenXML high-fidelity HTML and extracts structured tables.
 */
export async function parseDocxDocument(arrayBuffer: ArrayBuffer): Promise<DocxParseResult> {
  let html = '';
  let messages: string[] = [];

  if (typeof document !== 'undefined') {
    try {
      const sandbox = document.createElement('div');
      sandbox.className = 'docx-preview-sandbox';

      await renderAsync(arrayBuffer.slice(0), sandbox, null, {
        inWrapper: false,
        ignoreWidth: true,
        ignoreHeight: true,
        ignoreFonts: true, // Use local system fonts instantly (zero network latency & zero font blob overhead)
        breakPages: false,
        experimental: false,
        useBase64URL: true,
        renderHeaders: true,
        renderFooters: true,
      });

      // Extract all scoped <style> tags generated by docx-preview
      const styleTags = Array.from(sandbox.querySelectorAll('style'))
        .map((s) => s.outerHTML)
        .join('\n');

      // Extract inner rendered content
      const docxSections = sandbox.querySelectorAll('.docx, section.docx, article.docx');
      let bodyContent = '';
      if (docxSections.length > 0) {
        docxSections.forEach((sec) => {
          bodyContent += sec.outerHTML;
        });
      } else {
        bodyContent = sandbox.innerHTML;
      }

      if (bodyContent && bodyContent.trim().length > 0) {
        html = `${styleTags}\n<div class="docx-parsed-body">${bodyContent}</div>`;
      }
    } catch (e) {
      console.warn('docx-preview rendering failed, falling back to mammoth', e);
    }
  }

  // Fallback to mammoth if docx-preview is unavailable or produces empty HTML
  if (!html.trim()) {
    const options = {
      styleMap: [
        "p[style-name='Title'] => h1.doc-title:fresh",
        "p[style-name='Subtitle'] => h2.doc-subtitle:fresh",
        "p[style-name='Heading 1'] => h2.doc-heading-1:fresh",
        "p[style-name='Heading 2'] => h3.doc-heading-2:fresh",
        "p[style-name='Heading 3'] => h4.doc-heading-3:fresh",
        "table => table.w-full.border-collapse.border.border-slate-400:fresh",
        "tr => tr.border-b.border-slate-300:fresh",
        "th => th.py-1.5.px-2.5.border.border-slate-300.bg-slate-100.font-bold.text-slate-900:fresh",
        "td => td.py-1.5.px-2.5.border.border-slate-300.text-slate-800:fresh",
      ],
    };

    const result = await mammoth.convertToHtml({ arrayBuffer }, options);
    html = result.value || '';
    messages = (result.messages || []).map((m: any) => m.message || String(m));
  }

  // Extract placeholders matching {{field_name}} or {field_name}
  const detectedPlaceholders = detectPlaceholders(html);

  // Extract tables from HTML
  const { isTableDocument, extractedColumns, extractedRows } = extractTableDataFromHtml(html);

  return {
    html,
    messages,
    detectedPlaceholders,
    isTableDocument,
    extractedColumns,
    extractedRows,
  };
}

/**
 * Extracts structured table columns and rows from parsed HTML.
 */
export function extractTableDataFromHtml(html: string): {
  isTableDocument: boolean;
  extractedColumns: Array<{ id: string; header: string; label: string }>;
  extractedRows: Array<Record<string, any>>;
} {
  if (typeof document === 'undefined' || !html.includes('<table')) {
    return { isTableDocument: false, extractedColumns: [], extractedRows: [] };
  }

  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');
    const tableEl = doc.querySelector('table');
    if (!tableEl) {
      return { isTableDocument: false, extractedColumns: [], extractedRows: [] };
    }

    const trEls = Array.from(tableEl.querySelectorAll('tr'));
    if (trEls.length === 0) {
      return { isTableDocument: false, extractedColumns: [], extractedRows: [] };
    }

    // Identify headers from first row
    const firstRowCells = Array.from(trEls[0].querySelectorAll('th, td'));
    const columns = firstRowCells.map((cell, idx) => {
      const text = cell.textContent?.trim() || `Column ${idx + 1}`;
      const id = text.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '') || `col_${idx}`;
      return {
        id,
        header: text,
        label: text,
      };
    });

    // Extract remaining rows
    const dataRows = trEls.slice(1);
    const rows = dataRows.map((tr, rIdx) => {
      const cells = Array.from(tr.querySelectorAll('td, th'));
      const rowRecord: Record<string, any> = { id: `docx_row_${rIdx + 1}` };
      columns.forEach((col, cIdx) => {
        rowRecord[col.id] = cells[cIdx]?.textContent?.trim() || '';
      });
      return rowRecord;
    });

    return {
      isTableDocument: rows.length > 0,
      extractedColumns: columns,
      extractedRows: rows,
    };
  } catch (e) {
    console.warn('Failed to parse table from DOCX HTML', e);
    return { isTableDocument: false, extractedColumns: [], extractedRows: [] };
  }
}

/**
 * Cleans Word HTML by collapsing split run tags inside {{placeholders}} or {placeholders}.
 */
export function sanitizeDocxPlaceholders(html: string): string {
  if (!html) return '';
  // Collapse HTML tags between {{ and }}
  let cleaned = html.replace(/\{\{([\s\S]*?)\}\}/g, (match, inner) => {
    const stripped = inner.replace(/<[^>]*>/g, '').trim();
    return `{{${stripped}}}`;
  });
  // Collapse HTML tags between single { and } where it looks like a variable
  cleaned = cleaned.replace(/\{([a-zA-Z0-9_\-\.\s]{1,50})\}/g, (match, inner) => {
    const stripped = inner.replace(/<[^>]*>/g, '').trim();
    return `{{${stripped}}}`;
  });
  return cleaned;
}

/**
 * Detect all placeholder tokens like {{student_name}}, {{roll_number}}, {class} etc.
 */
export function detectPlaceholders(html: string): string[] {
  if (!html) return [];
  const sanitized = sanitizeDocxPlaceholders(html);
  const regex = /\{\{([a-zA-Z0-9_\-\.\s]+)\}\}/g;
  const placeholders = new Set<string>();
  let match;
  while ((match = regex.exec(sanitized)) !== null) {
    const token = (match[1] || '').trim();
    if (token) {
      placeholders.add(token);
    }
  }
  return Array.from(placeholders);
}

/**
 * Normalizes a variable name by lowercasing and stripping non-alphanumeric chars.
 */
function normalizeKey(str: string): string {
  return String(str || '').toLowerCase().replace(/[^a-z0-9]/g, '');
}

/**
 * Builds an enriched key-value lookup map supporting camelCase, snake_case, spaces, nested properties, and casing variations.
 * 100% Dynamic & Algorithmic - Zero hardcoded domain aliases.
 */
function buildEnrichedLookup(dataRecord: Record<string, any>): Map<string, string> {
  const map = new Map<string, string>();
  if (!dataRecord || typeof dataRecord !== 'object') return map;

  const insertKeyVariants = (rawKey: string, val: any) => {
    if (val === undefined || val === null) return;
    const strVal = typeof val === 'object' && !Array.isArray(val) ? JSON.stringify(val) : String(val);

    // 1. Raw exact key
    map.set(rawKey, strVal);

    // 2. Lowercase key
    const lowerKey = rawKey.toLowerCase();
    map.set(lowerKey, strVal);

    // 3. Alphanumeric stripped key (e.g. 'roll_number' -> 'rollnumber', 'student-name' -> 'studentname')
    const norm = normalizeKey(rawKey);
    if (norm) {
      map.set(norm, strVal);
    }

    // 4. camelCase to snake_case (e.g. 'studentName' -> 'student_name')
    const snakeCase = rawKey.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
    if (snakeCase && snakeCase !== lowerKey) {
      map.set(snakeCase, strVal);
      map.set(snakeCase.replace(/_/g, ' '), strVal);
    }

    // 5. snake_case to camelCase (e.g. 'student_name' -> 'studentName')
    const camelCase = rawKey.replace(/_([a-z0-9])/gi, (_, letter) => letter.toUpperCase());
    if (camelCase && camelCase !== rawKey) {
      map.set(camelCase, strVal);
      map.set(camelCase.toLowerCase(), strVal);
    }

    // 6. Space-separated variant (e.g. 'student_name' or 'studentName' -> 'student name')
    const spaceCase = rawKey.replace(/([A-Z])/g, ' $1').replace(/[_-]/g, ' ').replace(/\s+/g, ' ').trim().toLowerCase();
    if (spaceCase) {
      map.set(spaceCase, strVal);
    }
  };

  // Process all direct and nested properties
  Object.entries(dataRecord).forEach(([k, v]) => {
    insertKeyVariants(k, v);

    // If property is a nested object, flatten keys (e.g. { student: { name: 'Ali' } } -> 'student_name', 'student.name')
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      Object.entries(v).forEach(([subK, subV]) => {
        insertKeyVariants(`${k}_${subK}`, subV);
        insertKeyVariants(`${k}.${subK}`, subV);
      });
    }
  });

  return map;
}

/**
 * Splits docx HTML into distinct <style> blocks and body HTML content to prevent
 * massive style tag duplication when rendering multiple student pages.
 */
export function separateDocxStylesAndBody(html: string): { styles: string; body: string } {
  if (!html) return { styles: '', body: '' };

  const styleRegex = /<style\b[^>]*>[\s\S]*?<\/style>/gi;
  const styles: string[] = [];
  let match;
  while ((match = styleRegex.exec(html)) !== null) {
    styles.push(match[0]);
  }

  const body = html.replace(styleRegex, '').trim();
  return {
    styles: styles.join('\n'),
    body,
  };
}

/**
 * Merges template HTML with a single record or multiple records with smart fuzzy key matching.
 */
export function mergeTemplateWithData(
  templateHtml: string,
  dataRecord: Record<string, any>
): string {
  if (!templateHtml || !dataRecord) return templateHtml;
  const sanitized = sanitizeDocxPlaceholders(templateHtml);
  const lookup = buildEnrichedLookup(dataRecord);

  // Match any {{placeholder}} or {placeholder}
  const merged = sanitized.replace(/\{\{([\s\S]*?)\}\}/g, (fullMatch, token) => {
    const rawKey = token.trim();
    const norm = normalizeKey(rawKey);
    if (lookup.has(norm)) {
      return lookup.get(norm)!;
    }
    if (lookup.has(rawKey.toLowerCase())) {
      return lookup.get(rawKey.toLowerCase())!;
    }
    if (lookup.has(rawKey)) {
      return lookup.get(rawKey)!;
    }
    // Return original placeholder if no value is found
    return fullMatch;
  });

  return merged;
}

/**
 * Ultra-fast bulk merges template HTML across multiple records into distinct printable page HTML blocks.
 * Sanitizes template ONCE, avoids repeated regex compiling, and separates styles to prevent CSSOM lockup.
 */
export function bulkMergeTemplate(
  templateHtml: string,
  records: Array<Record<string, any>>
): string[] {
  if (!records || records.length === 0) {
    return [templateHtml];
  }

  // Separate style tags from template body so styles aren't duplicated 100 times in memory
  const { styles, body } = separateDocxStylesAndBody(templateHtml);
  const targetBody = body || templateHtml;

  // Sanitize template body ONCE instead of inside every record loop
  const sanitizedBody = sanitizeDocxPlaceholders(targetBody);
  const placeholderRegex = /\{\{([\s\S]*?)\}\}/g;

  return records.map((record) => {
    const lookup = buildEnrichedLookup(record);
    const merged = sanitizedBody.replace(placeholderRegex, (fullMatch, token) => {
      const rawKey = token.trim();
      const norm = normalizeKey(rawKey);
      if (lookup.has(norm)) {
        return lookup.get(norm)!;
      }
      const lower = rawKey.toLowerCase();
      if (lookup.has(lower)) {
        return lookup.get(lower)!;
      }
      if (lookup.has(rawKey)) {
        return lookup.get(rawKey)!;
      }
      return fullMatch;
    });

    return styles ? `${styles}\n${merged}` : merged;
  });
}

/**
 * LocalStorage Custom Template Repository
 */
export function getSavedDocxTemplates(): CustomDocxTemplate[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(TEMPLATES_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed;
    }
  } catch (e) {
    console.warn('Failed to load saved docx templates', e);
  }
  return [];
}

export function saveDocxTemplate(template: Omit<CustomDocxTemplate, 'createdAt' | 'updatedAt'>): CustomDocxTemplate {
  const existing = getSavedDocxTemplates();
  const now = new Date().toISOString();
  const newTemplate: CustomDocxTemplate = {
    ...template,
    createdAt: now,
    updatedAt: now,
  };

  const filtered = existing.filter((t) => t.id !== template.id);
  const updated = [newTemplate, ...filtered];

  if (typeof window !== 'undefined') {
    try {
      localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(updated));
    } catch (e) {
      console.warn('Failed to save docx template to localStorage', e);
    }
  }

  return newTemplate;
}

export function deleteDocxTemplate(id: string): boolean {
  const existing = getSavedDocxTemplates();
  const updated = existing.filter((t) => t.id !== id);

  if (typeof window !== 'undefined') {
    try {
      localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(updated));
      return true;
    } catch (e) {
      console.warn('Failed to delete docx template', e);
    }
  }
  return false;
}

export interface TemplatePlaceholderKey {
  key: string;
  label: string;
  category?: 'student' | 'examination' | 'institution' | 'academic' | 'general' | 'custom' | string;
  sampleValue?: string;
  description?: string;
  isCustom?: boolean;
}

export interface ExtractKeysOptions {
  moduleKeys?: TemplatePlaceholderKey[];
  sampleData?: Record<string, any>;
  columns?: Array<{ id: string; header?: string; label?: string }>;
  metaItems?: Array<{ label: string; value: any }>;
  customKeys?: TemplatePlaceholderKey[];
}

/**
 * Extracts and consolidates all available dynamic placeholder keys strictly based on active context.
 * When moduleKeys are provided by the caller module, it strictly adheres to that schema and enriches with live data.
 * 100% Dynamic & Schema-Driven - Zero hardcoded static fallback arrays.
 */
export function extractAvailableKeysFromContext(
  sampleDataOrOptions?: ExtractKeysOptions | Record<string, any>,
  columns?: Array<{ id: string; header?: string; label?: string }>,
  customKeys?: TemplatePlaceholderKey[],
  moduleKeys?: TemplatePlaceholderKey[],
  metaItems?: Array<{ label: string; value: any }>
): TemplatePlaceholderKey[] {
  const map = new Map<string, TemplatePlaceholderKey>();

  let activeModuleKeys: TemplatePlaceholderKey[] = [];
  let activeSampleData: Record<string, any> | undefined;
  let activeColumns: Array<{ id: string; header?: string; label?: string }> | undefined;
  let activeMetaItems: Array<{ label: string; value: any }> | undefined;
  let activeCustomKeys: TemplatePlaceholderKey[] = [];

  if (sampleDataOrOptions && typeof sampleDataOrOptions === 'object' && 'moduleKeys' in sampleDataOrOptions) {
    // Options object overload
    const opts = sampleDataOrOptions as ExtractKeysOptions;
    activeModuleKeys = opts.moduleKeys || [];
    activeSampleData = opts.sampleData;
    activeColumns = opts.columns;
    activeMetaItems = opts.metaItems;
    activeCustomKeys = opts.customKeys || [];
  } else {
    // Positional parameters overload
    activeSampleData = sampleDataOrOptions as Record<string, any>;
    activeColumns = columns;
    activeCustomKeys = customKeys || [];
    activeModuleKeys = moduleKeys || [];
    activeMetaItems = metaItems;
  }

  // Helper lookup for live sample data enrichment
  const sampleLookup =
    activeSampleData && typeof activeSampleData === 'object'
      ? buildEnrichedLookup(activeSampleData)
      : null;

  // Case A: Module-provided placeholder keys (Strict Curated Schema for the active document)
  if (Array.isArray(activeModuleKeys) && activeModuleKeys.length > 0) {
    activeModuleKeys.forEach((item) => {
      if (item && item.key) {
        const keyId = item.key.toLowerCase().trim();
        let liveVal = item.sampleValue;

        if (sampleLookup) {
          const found =
            sampleLookup.get(keyId) ||
            sampleLookup.get(normalizeKey(keyId)) ||
            sampleLookup.get(item.key);
          if (found !== undefined && found !== null && found !== '[object Object]' && found !== '') {
            liveVal = found;
          }
        }

        map.set(keyId, {
          ...item,
          sampleValue: liveVal,
          category: item.category || 'general',
        });
      }
    });

    // Add user custom keys
    if (Array.isArray(activeCustomKeys)) {
      activeCustomKeys.forEach((ck) => {
        if (ck && ck.key) {
          const keyId = ck.key.toLowerCase().trim();
          let liveVal = ck.sampleValue;
          if (sampleLookup) {
            const found = sampleLookup.get(keyId) || sampleLookup.get(normalizeKey(keyId));
            if (found !== undefined && found !== null && found !== '[object Object]') {
              liveVal = found;
            }
          }
          map.set(keyId, { ...ck, sampleValue: liveVal, category: 'custom', isCustom: true });
        }
      });
    }

    return Array.from(map.values());
  }

  // Case B: Dynamic Fallback when no explicit moduleKeys are provided (Tabular grids / Generic documents)
  if (Array.isArray(activeColumns) && activeColumns.length > 0) {
    activeColumns.forEach((col) => {
      if (!col) return;
      const colId = (col.id || col.header || col.label || '').replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      if (colId && !map.has(colId)) {
        let liveVal = `[${col.label || col.header || col.id}]`;
        if (sampleLookup) {
          const found = sampleLookup.get(colId) || sampleLookup.get(normalizeKey(colId));
          if (found !== undefined && found !== null && found !== '[object Object]') {
            liveVal = found;
          }
        }
        map.set(colId, {
          key: colId,
          label: col.label || col.header || col.id,
          category: 'academic',
          sampleValue: liveVal,
          description: `Table column field`,
        });
      }
    });
  } else if (activeSampleData && typeof activeSampleData === 'object') {
    Object.entries(activeSampleData).forEach(([rawKey, val]) => {
      if (val === undefined || val === null || typeof val === 'function') return;
      if (['id', '_id', '__v', 'key', 'children', 'isEditable'].includes(rawKey)) return;
      if (typeof val === 'object' && Array.isArray(val)) return;

      const formattedKey = rawKey.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      const humanLabel = rawKey
        .replace(/([A-Z])/g, ' $1')
        .replace(/[_-]/g, ' ')
        .trim()
        .replace(/^./, (s) => s.toUpperCase());

      map.set(formattedKey, {
        key: formattedKey,
        label: humanLabel,
        category: 'general',
        sampleValue: typeof val === 'object' ? JSON.stringify(val) : String(val),
        description: `Field from document data`,
      });
    });
  }

  // Dynamic extraction from metaItems (e.g. [{ label: 'Class', value: 'Class 10' }])
  if (Array.isArray(activeMetaItems)) {
    activeMetaItems.forEach((meta) => {
      if (!meta || !meta.label) return;
      const metaKey = meta.label.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      if (metaKey && !map.has(metaKey)) {
        map.set(metaKey, {
          key: metaKey,
          label: meta.label,
          category: 'general',
          sampleValue: String(meta.value || ''),
          description: `Document header metadata`,
        });
      }
    });
  }

  // User-defined custom dynamic keys
  if (Array.isArray(activeCustomKeys)) {
    activeCustomKeys.forEach((ck) => {
      if (ck && ck.key) {
        const keyId = ck.key.toLowerCase().trim();
        map.set(keyId, { ...ck, category: 'custom', isCustom: true });
      }
    });
  }

  return Array.from(map.values());
}

