import { renderAsync } from 'docx-preview';
import mammoth from 'mammoth';

export type DocxTemplateType = 'template' | 'generated';

export interface CustomDocxTemplate {
  id: string;
  name: string;
  description?: string;
  scopeId?: string;
  rawHtml: string;
  detectedPlaceholders: string[];
  createdAt: string;
  updatedAt: string;
  isTableDocument?: boolean;
  sampleColumns?: Array<{ id: string; header: string; label: string }>;
  sampleData?: Array<Record<string, any>>;
  templateType?: DocxTemplateType;
  recordsCount?: number;
  sourceTemplateId?: string;
}

export interface DocxParseResult {
  html: string;
  messages: string[];
  detectedPlaceholders: string[];
  isTableDocument: boolean;
  extractedColumns: Array<{ id: string; header: string; label: string }>;
  extractedRows: Array<Record<string, any>>;
}

const TEMPLATES_STORAGE_KEY = 'spr_custom_docx_templates';

export const UNIVERSAL_SYNONYM_GROUPS: string[][] = [
  ['name', 'student_name', 'studentname', 'student_full_name', 'fullname', 'staff_name', 'employee_name'],
  ['roll', 'roll_number', 'rollnumber', 'roll_no', 'rollno'],
  ['class', 'class_name', 'classname', 'class_section'],
  ['section', 'section_name', 'sectionname'],
  ['grade', 'letter_grade', 'overall_grade'],
  ['exam', 'exam_name', 'examname', 'examination', 'exam_title'],
  ['session', 'academic_session', 'academicsession', 'academic_year', 'academicyear'],
  ['department', 'department_name', 'departmentname'],
  ['institution', 'institution_name', 'institutionname', 'school_name', 'schoolname', 'academy_name', 'academyname'],
  ['total', 'total_marks', 'totalmarks', 'grand_total'],
  ['obtained', 'obtained_marks', 'obtainedmarks', 'total_obtained', 'totalobtained'],
  ['student_id', 'studentid', 'student_uniq_id', 'reg_no', 'regno', 'uniq_id', 'student_code'],
  ['highest_marks', 'highestmarks', 'highest', 'highest_total', 'highestmark'],
  ['highest_gpa', 'highestgpa'],
  ['highest_percentage', 'highestpercentage'],
  ['subject', 'subject_name', 'subjectname', 'course_name', 'course'],
  ['full_marks', 'fullmarks', 'full'],
  ['pass_marks', 'passmarks', 'pass'],
  ['cq_marks', 'cqmarks', 'cq', 'creative'],
  ['mcq_marks', 'mcqmarks', 'mcq'],
  ['practical_marks', 'practicalmarks', 'practical', 'pr'],
  ['ca_marks', 'camarks', 'ca', 'continuous'],
  ['voucher_no', 'voucher', 'invoice_no', 'bill_no'],
  ['fee_amount', 'amount', 'payable_amount', 'total_fee'],
  ['paid_amount', 'paid', 'total_paid'],
  ['due_amount', 'due', 'balance'],
  ['employee_id', 'staff_id', 'emp_id'],
  ['designation', 'designation_name', 'post', 'job_title'],
];

/**
 * Parses a Word document (.docx) ArrayBuffer into 100% exact OpenXML high-fidelity HTML and extracts structured tables.
 */
export async function parseDocxDocument(arrayBuffer: ArrayBuffer): Promise<DocxParseResult> {
  let html = '';
  let messages: string[] = [];

  if (typeof document !== 'undefined') {
    try {
      const sandbox = document.createElement('div');
      sandbox.className = 'docx-preview-sandbox';

      await renderAsync(arrayBuffer.slice(0), sandbox, null, {
        inWrapper: false,
        ignoreWidth: true,
        ignoreHeight: true,
        ignoreFonts: true, // Use local system fonts instantly (zero network latency & zero font blob overhead)
        breakPages: false,
        experimental: false,
        useBase64URL: true,
        renderHeaders: true,
        renderFooters: true,
      });

      // Extract all scoped <style> tags generated by docx-preview
      const styleTags = Array.from(sandbox.querySelectorAll('style'))
        .map((s) => s.outerHTML)
        .join('\n');

      // Extract inner rendered content
      const docxSections = sandbox.querySelectorAll('.docx, section.docx, article.docx');
      let bodyContent = '';
      if (docxSections.length > 0) {
        docxSections.forEach((sec) => {
          bodyContent += sec.outerHTML;
        });
      } else {
        bodyContent = sandbox.innerHTML;
      }

      if (bodyContent && bodyContent.trim().length > 0) {
        html = `${styleTags}\n<div class="docx-parsed-body">${bodyContent}</div>`;
      }
    } catch (e) {
      console.warn('docx-preview rendering failed, falling back to mammoth', e);
    }
  }

  // Fallback to mammoth if docx-preview is unavailable or produces empty HTML
  if (!html.trim()) {
    const options = {
      styleMap: [
        "p[style-name='Title'] => h1.doc-title:fresh",
        "p[style-name='Subtitle'] => h2.doc-subtitle:fresh",
        "p[style-name='Heading 1'] => h2.doc-heading-1:fresh",
        "p[style-name='Heading 2'] => h3.doc-heading-2:fresh",
        "p[style-name='Heading 3'] => h4.doc-heading-3:fresh",
        "table => table.w-full.border-collapse.border.border-slate-400:fresh",
        "tr => tr.border-b.border-slate-300:fresh",
        "th => th.py-1.5.px-2.5.border.border-slate-300.bg-slate-100.font-bold.text-slate-900:fresh",
        "td => td.py-1.5.px-2.5.border.border-slate-300.text-slate-800:fresh",
      ],
    };

    const result = await mammoth.convertToHtml({ arrayBuffer }, options);
    html = result.value || '';
    messages = (result.messages || []).map((m: any) => m.message || String(m));
  }

  // Extract placeholders matching {{field_name}} or {field_name}
  const detectedPlaceholders = detectPlaceholders(html);

  // Extract tables from HTML
  const { isTableDocument, extractedColumns, extractedRows } = extractTableDataFromHtml(html);

  return {
    html,
    messages,
    detectedPlaceholders,
    isTableDocument,
    extractedColumns,
    extractedRows,
  };
}

/**
 * Extracts structured table columns and rows from parsed HTML.
 */
export function extractTableDataFromHtml(html: string): {
  isTableDocument: boolean;
  extractedColumns: Array<{ id: string; header: string; label: string }>;
  extractedRows: Array<Record<string, any>>;
} {
  if (typeof document === 'undefined' || !html.includes('<table')) {
    return { isTableDocument: false, extractedColumns: [], extractedRows: [] };
  }

  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');
    const tableEl = doc.querySelector('table');
    if (!tableEl) {
      return { isTableDocument: false, extractedColumns: [], extractedRows: [] };
    }

    const trEls = Array.from(tableEl.querySelectorAll('tr'));
    if (trEls.length === 0) {
      return { isTableDocument: false, extractedColumns: [], extractedRows: [] };
    }

    // Identify headers from first row
    const firstRowCells = Array.from(trEls[0].querySelectorAll('th, td'));
    const columns = firstRowCells.map((cell, idx) => {
      const text = cell.textContent?.trim() || `Column ${idx + 1}`;
      const id = text.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '') || `col_${idx}`;
      return {
        id,
        header: text,
        label: text,
      };
    });

    // Extract remaining rows
    const dataRows = trEls.slice(1);
    const rows = dataRows.map((tr, rIdx) => {
      const cells = Array.from(tr.querySelectorAll('td, th'));
      const rowRecord: Record<string, any> = { id: `docx_row_${rIdx + 1}` };
      columns.forEach((col, cIdx) => {
        rowRecord[col.id] = cells[cIdx]?.textContent?.trim() || '';
      });
      return rowRecord;
    });

    return {
      isTableDocument: rows.length > 0,
      extractedColumns: columns,
      extractedRows: rows,
    };
  } catch (e) {
    console.warn('Failed to parse table from DOCX HTML', e);
    return { isTableDocument: false, extractedColumns: [], extractedRows: [] };
  }
}

/**
 * Cleans Word HTML by collapsing split run tags inside {{placeholders}} or {placeholders}.
 * Strictly prevents brace expansion (e.g. {{key}} never becomes {{{key}}}).
 */
export function sanitizeDocxPlaceholders(html: string): string {
  if (!html) return '';

  // 1. Collapse HTML tags between {{ and }}
  let cleaned = html.replace(/\{\{([\s\S]*?)\}\}/g, (match, inner) => {
    const stripped = inner.replace(/<[^>]*>/g, '').trim();
    const cleanKey = stripped.replace(/^\{+/, '').replace(/\}+$/, '').trim();
    return `{{${cleanKey}}}`;
  });

  // 2. Collapse standalone single {variable} ONLY if not preceded or followed by { or }
  cleaned = cleaned.replace(/(?<!\{)\{([a-zA-Z0-9_\-\.\s]{1,50})\}(?!\})/g, (match, inner) => {
    const stripped = inner.replace(/<[^>]*>/g, '').trim();
    const cleanKey = stripped.replace(/^\{+/, '').replace(/\}+$/, '').trim();
    return `{{${cleanKey}}}`;
  });

  // 3. Prevent and collapse any accidental triple or quadruple braces: {{{key}}} -> {{key}}
  cleaned = cleaned.replace(/\{{3,}([a-zA-Z0-9_\-\.\s]+)\}{3,}/g, (_, key) => `{{${key.trim()}}}`);

  return cleaned;
}

/**
 * Detect all placeholder tokens like {{student_name}}, {{roll_number}}, {class} etc.
 */
export function detectPlaceholders(html: string): string[] {
  if (!html) return [];
  const sanitized = sanitizeDocxPlaceholders(html);
  const regex = /\{\{([a-zA-Z0-9_\-\.\s]+)\}\}/g;
  const placeholders = new Set<string>();
  let match;
  while ((match = regex.exec(sanitized)) !== null) {
    const token = (match[1] || '').trim();
    if (token) {
      placeholders.add(token);
    }
  }
  return Array.from(placeholders);
}

/**
 * Normalizes a variable name by lowercasing and stripping non-alphanumeric chars.
 */
function normalizeKey(str: string): string {
  return String(str || '').toLowerCase().replace(/[^a-z0-9]/g, '');
}

/**
 * Builds an enriched key-value lookup map supporting camelCase, snake_case, spaces, nested properties, and casing variations.
 * 100% Dynamic & Algorithmic with smart universal domain alias resolution.
 */
function buildEnrichedLookup(dataRecord: Record<string, any>): Map<string, string> {
  const map = new Map<string, string>();
  if (!dataRecord || typeof dataRecord !== 'object') return map;

  const insertKeyVariants = (rawKey: string, val: any) => {
    if (val === undefined || val === null) return;
    const strVal = typeof val === 'object' && !Array.isArray(val) ? JSON.stringify(val) : String(val);

    // 1. Raw exact key
    map.set(rawKey, strVal);

    // 2. Lowercase key
    const lowerKey = rawKey.toLowerCase();
    map.set(lowerKey, strVal);

    // 3. Alphanumeric stripped key (e.g. 'roll_number' -> 'rollnumber', 'student-name' -> 'studentname')
    const norm = normalizeKey(rawKey);
    if (norm) {
      map.set(norm, strVal);
    }

    // 4. camelCase to snake_case (e.g. 'studentName' -> 'student_name')
    const snakeCase = rawKey.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
    if (snakeCase && snakeCase !== lowerKey) {
      map.set(snakeCase, strVal);
      map.set(snakeCase.replace(/_/g, ' '), strVal);
    }

    // 5. snake_case to camelCase (e.g. 'student_name' -> 'studentName')
    const camelCase = rawKey.replace(/_([a-z0-9])/gi, (_, letter) => letter.toUpperCase());
    if (camelCase && camelCase !== rawKey) {
      map.set(camelCase, strVal);
      map.set(camelCase.toLowerCase(), strVal);
    }

    // 6. Space-separated variant (e.g. 'student_name' or 'studentName' -> 'student name')
    const spaceCase = rawKey.replace(/([A-Z])/g, ' $1').replace(/[_-]/g, ' ').replace(/\s+/g, ' ').trim().toLowerCase();
    if (spaceCase) {
      map.set(spaceCase, strVal);
    }

    // 7. Universal Declarative Synonym Matching
    for (const group of UNIVERSAL_SYNONYM_GROUPS) {
      if (group.some((syn) => syn.replace(/[^a-z0-9]/g, '') === norm)) {
        group.forEach((syn) => {
          map.set(syn, strVal);
          map.set(syn.replace(/[^a-z0-9]/g, ''), strVal);
        });
        break;
      }
    }
  };

  // Process all direct and nested properties
  Object.entries(dataRecord).forEach(([k, v]) => {
    insertKeyVariants(k, v);

    // If property is a nested object, flatten keys (e.g. { student: { name: 'Ali' } } -> 'student_name', 'student.name')
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      Object.entries(v).forEach(([subK, subV]) => {
        insertKeyVariants(`${k}_${subK}`, subV);
        insertKeyVariants(`${k}.${subK}`, subV);
      });
    }
  });

  return map;
}

/**
 * Splits docx HTML into distinct <style> blocks and body HTML content to prevent
 * massive style tag duplication when rendering multiple student pages.
 */
export function separateDocxStylesAndBody(html: string): { styles: string; body: string } {
  if (!html) return { styles: '', body: '' };

  const styleRegex = /<style\b[^>]*>[\s\S]*?<\/style>/gi;
  const styles: string[] = [];
  let match;
  while ((match = styleRegex.exec(html)) !== null) {
    styles.push(match[0]);
  }

  const body = html.replace(styleRegex, '').trim();
  return {
    styles: styles.join('\n'),
    body,
  };
}

/**
 * Detects if a template is a Tabular Template (Type 1) containing repeating table rows or loop tags.
 */
export function isTabularTemplate(html: string): boolean {
  if (!html) return false;
  // 1. Explicit loop block markers (e.g. {{#rows}}, {{#students}}, {{#records}})
  if (/\{\{#(rows|students|records|data|items|table|list|row)\}\}/i.test(html)) {
    return true;
  }

  // 2. DOM-based table check with repeating placeholders
  if (typeof document !== 'undefined' && html.includes('<table')) {
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(html, 'text/html');
      const tables = doc.querySelectorAll('table');
      for (const table of Array.from(tables)) {
        const rows = table.querySelectorAll('tr');
        for (const tr of Array.from(rows)) {
          // Check if this row contains {{...}} placeholders and is not purely <th> header cells
          const hasPlaceholders = /\{\{([a-zA-Z0-9_\-\.\s]+)\}\}/.test(tr.innerHTML);
          const hasOnlyTh = tr.querySelectorAll('th').length > 0 && tr.querySelectorAll('td').length === 0;
          if (hasPlaceholders && !hasOnlyTh) {
            return true;
          }
        }
      }
    } catch (e) {
      // fallback to regex
    }
  }

  // 3. Fallback regex for tables containing placeholders inside <td>
  const tdPlaceholderRegex = /<tr\b[^>]*>[\s\S]*?<td\b[^>]*>[\s\S]*?\{\{([a-zA-Z0-9_\-\.\s]+)\}\}[\s\S]*?<\/td>[\s\S]*?<\/tr>/i;
  return tdPlaceholderRegex.test(html);
}

/**
 * Type 1: Tabular Column-Loop / Table Data Row Merging Engine
 * Merges a table template with an array of records by repeating the template data row
 * for each record, populating column variables and sequential index (Sl/No/Index).
 */
export function mergeTabularTemplateWithData(
  templateHtml: string,
  records: Array<Record<string, any>>,
  baseContext: Record<string, any> = {}
): string {
  if (!templateHtml) return '';
  if (!Array.isArray(records) || records.length === 0) {
    return mergeTemplateWithData(templateHtml, baseContext);
  }

  const sanitized = sanitizeDocxPlaceholders(templateHtml);

  // 1. Check for explicit loop block syntax: {{#rows}} ... {{/rows}}
  const loopBlockRegex = /\{\{#(rows|students|records|data|items|table|list|row)\}\}([\s\S]*?)\{\{\/\1\}\}/gi;
  if (loopBlockRegex.test(sanitized)) {
    const expanded = sanitized.replace(loopBlockRegex, (_, _tagName, blockContent) => {
      return records
        .map((rec, rIdx) => {
          const rowData = {
            sl: rIdx + 1,
            serial: rIdx + 1,
            no: rIdx + 1,
            index: rIdx + 1,
            row_num: rIdx + 1,
            row_number: rIdx + 1,
            index_0: rIdx,
            '@index': rIdx + 1,
            '#index': rIdx + 1,
            ...baseContext,
            ...rec,
          };
          return mergeTemplateWithData(blockContent, rowData);
        })
        .join('\n');
    });

    const finalContext = {
      ...baseContext,
      total_students: records.length,
      total_records: records.length,
      records_count: records.length,
      total_count: records.length,
    };
    return mergeTemplateWithData(expanded, finalContext);
  }

  // 2. Implicit Table Row Detection via DOMParser
  if (typeof document !== 'undefined' && sanitized.includes('<table')) {
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(sanitized, 'text/html');
      const tables = doc.querySelectorAll('table');
      let tableFoundAndProcessed = false;

      tables.forEach((table) => {
        const trEls = Array.from(table.querySelectorAll('tr'));
        // Find the template row: a <tr> that contains <td> cells with {{...}} placeholders
        const templateRow = trEls.find((tr) => {
          const cells = tr.querySelectorAll('td');
          if (cells.length === 0) return false;
          return /\{\{([a-zA-Z0-9_\-\.\s]+)\}\}/.test(tr.innerHTML);
        });

        if (templateRow && templateRow.parentNode) {
          tableFoundAndProcessed = true;
          const parent = templateRow.parentNode;
          const rowTemplateHtml = templateRow.outerHTML;

          // Generate a populated row for each record
          records.forEach((rec, rIdx) => {
            const rowData = {
              sl: rIdx + 1,
              serial: rIdx + 1,
              no: rIdx + 1,
              index: rIdx + 1,
              row_num: rIdx + 1,
              row_number: rIdx + 1,
              index_0: rIdx,
              '@index': rIdx + 1,
              '#index': rIdx + 1,
              ...baseContext,
              ...rec,
            };

            const populatedRowHtml = mergeTemplateWithData(rowTemplateHtml, rowData);
            const tempContainer = doc.createElement('tbody');
            tempContainer.innerHTML = populatedRowHtml;
            const newTr = tempContainer.firstElementChild;
            if (newTr) {
              parent.insertBefore(newTr, templateRow);
            }
          });

          // Remove the placeholder template row
          parent.removeChild(templateRow);
        }
      });

      if (tableFoundAndProcessed) {
        const bodyContent = doc.body.innerHTML;
        const finalContext = {
          ...baseContext,
          total_students: records.length,
          total_records: records.length,
          records_count: records.length,
          total_count: records.length,
        };
        return mergeTemplateWithData(bodyContent, finalContext);
      }
    } catch (e) {
      console.warn('DOM table parsing failed in mergeTabularTemplateWithData, falling back to regex', e);
    }
  }

  // 3. Fallback Regex for single-table row template
  const rowRegex = /<tr\b[^>]*>[\s\S]*?<td\b[^>]*>[\s\S]*?\{\{([a-zA-Z0-9_\-\.\s]+)\}\}[\s\S]*?<\/td>[\s\S]*?<\/tr>/i;
  const match = rowRegex.exec(sanitized);
  if (match) {
    const templateTr = match[0];
    const repeatedRows = records
      .map((rec, rIdx) => {
        const rowData = {
          sl: rIdx + 1,
          serial: rIdx + 1,
          no: rIdx + 1,
          index: rIdx + 1,
          row_num: rIdx + 1,
          row_number: rIdx + 1,
          index_0: rIdx,
          '@index': rIdx + 1,
          '#index': rIdx + 1,
          ...baseContext,
          ...rec,
        };
        return mergeTemplateWithData(templateTr, rowData);
      })
      .join('\n');

    const expanded = sanitized.replace(templateTr, repeatedRows);
    const finalContext = {
      ...baseContext,
      total_students: records.length,
      total_records: records.length,
      records_count: records.length,
      total_count: records.length,
    };
    return mergeTemplateWithData(expanded, finalContext);
  }

  return mergeTemplateWithData(sanitized, baseContext);
}

/**
 * Universal Nested Array and Table Row Expansion Engine.
 * 100% Domain-Agnostic: Discovers any nested array of objects inside dataRecord
 * (e.g. subjectMarks, feeItems, items, records, rows, data) and dynamically
 * expands explicit loop tags ({{#arrayKey}} ... {{/arrayKey}}) or repeating table rows.
 */
function expandNestedArraysAndTables(html: string, dataRecord: Record<string, any>): string {
  if (!html || !dataRecord || typeof dataRecord !== 'object') return html;

  let result = html;

  // Find all array properties in dataRecord containing objects
  const arrayEntries = Object.entries(dataRecord).filter(
    ([_, val]) => Array.isArray(val) && val.length > 0 && typeof val[0] === 'object'
  );

  if (arrayEntries.length === 0) {
    return result;
  }

  // 1. Universal Explicit Loop Tags: {{#arrayKey}} ... {{/arrayKey}}
  arrayEntries.forEach(([arrayKey, items]) => {
    const loopRegex = new RegExp(`\\{\\{#(${arrayKey}|items|rows|list|data)\\}\\}([\\s\\S]*?)\\{\\{/\\1\\}\\}`, 'gi');
    if (loopRegex.test(result)) {
      result = result.replace(loopRegex, (_, _tagName, blockContent) => {
        return items
          .map((item: any, idx: number) => {
            const enrichedItem = {
              sl: idx + 1,
              serial: idx + 1,
              index: idx + 1,
              no: idx + 1,
              ...item,
            };
            return mergeTemplateWithData(blockContent, enrichedItem);
          })
          .join('\n');
      });
    }
  });

  // 2. Universal DOM-Based Repeating Table Row Detection
  if (typeof document !== 'undefined' && result.includes('<table')) {
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(result, 'text/html');
      const tables = doc.querySelectorAll('table');
      let tableModified = false;

      tables.forEach((table) => {
        const trEls = Array.from(table.querySelectorAll('tr'));
        if (trEls.length === 0) return;

        // Try to match this table against any array in arrayEntries
        for (const [_, items] of arrayEntries) {
          if (!Array.isArray(items) || items.length === 0) continue;

          // Collect all known keys present in this array's items
          const sampleItem = items[0] || {};
          const itemKeys = Object.keys(sampleItem).map((k) => k.toLowerCase());

          // Find a template <tr> that contains placeholders matching keys in this array's items
          const templateTr = trEls.find((tr, rIdx) => {
            const cells = tr.querySelectorAll('td');
            if (cells.length === 0) return false;

            // Skip top row if it's purely header (<th>)
            if (rIdx === 0 && trEls.length > 1 && tr.querySelectorAll('th').length > 0) {
              return false;
            }

            const inner = tr.innerHTML.toLowerCase();
            const placeholders = detectPlaceholders(inner);

            // Check if row placeholders match keys in the array
            const matchesArrayKeys = placeholders.some((p) => {
              const norm = normalizeKey(p);
              return itemKeys.some((k) => normalizeKey(k) === norm);
            });

            // Or if first cell contains sample placeholder text like "Subject 1", "Item 1", "Row 1"
            const hasSamplePattern = /(subject|item|row|entry|record)\s*[-_]?\s*0?1\b/i.test(inner);

            return matchesArrayKeys || hasSamplePattern;
          });

          if (templateTr && templateTr.parentNode) {
            tableModified = true;
            const parent = templateTr.parentNode;
            let rowTemplateHtml = templateTr.outerHTML;

            // Replace generic sample text like "Subject 1", "Item 1" in column with first item name key
            const preferredNameKey =
              Object.keys(sampleItem).find((k) =>
                ['subject_name', 'subjectname', 'item_name', 'itemname', 'name', 'title', 'label', 'description'].includes(k.toLowerCase())
              ) ||
              Object.keys(sampleItem).find((k) =>
                typeof sampleItem[k] === 'string' &&
                !k.toLowerCase().includes('id') &&
                !k.toLowerCase().includes('key') &&
                !k.toLowerCase().includes('code') &&
                !k.toLowerCase().includes('status') &&
                k !== 'sl' &&
                k !== 'index'
              ) ||
              'name';

            rowTemplateHtml = rowTemplateHtml.replace(/(subject|item|row|entry|record)\s*[-_]?\s*0?1\b/gi, `{{${preferredNameKey}}}`);

            items.forEach((item: any, idx: number) => {
              const enrichedItem = {
                sl: idx + 1,
                serial: idx + 1,
                index: idx + 1,
                no: idx + 1,
                ...item,
              };
              const populatedTrHtml = mergeTemplateWithData(rowTemplateHtml, enrichedItem);
              const temp = doc.createElement('tbody');
              temp.innerHTML = populatedTrHtml;
              const newRow = temp.firstElementChild;
              if (newRow) {
                parent.insertBefore(newRow, templateTr);
              }
            });

            parent.removeChild(templateTr);
            break; // Table processed for this array
          }
        }
      });

      if (tableModified) {
        result = doc.body.innerHTML;
      }
    } catch (e) {
      console.warn('Universal table expansion failed in mergeTemplateWithData', e);
    }
  }

  return result;
}

/**
 * Merges template HTML with a single record or multiple records with smart fuzzy key matching.
 */
export function mergeTemplateWithData(
  templateHtml: string,
  dataRecord: Record<string, any>
): string {
  if (!templateHtml || !dataRecord) return templateHtml;
  let sanitized = sanitizeDocxPlaceholders(templateHtml);

  // Expand any nested arrays or repeating table rows generically
  sanitized = expandNestedArraysAndTables(sanitized, dataRecord);

  const lookup = buildEnrichedLookup(dataRecord);

  // Match any {{placeholder}} or {placeholder}
  const merged = sanitized.replace(/\{\{([\s\S]*?)\}\}/g, (fullMatch, token) => {
    const rawKey = token.trim();
    const norm = normalizeKey(rawKey);
    if (lookup.has(norm)) {
      return lookup.get(norm)!;
    }
    if (lookup.has(rawKey.toLowerCase())) {
      return lookup.get(rawKey.toLowerCase())!;
    }
    if (lookup.has(rawKey)) {
      return lookup.get(rawKey)!;
    }
    // Return original placeholder if no value is found
    return fullMatch;
  });

  return merged;
}

/**
 * Ultra-fast bulk merges template HTML across multiple records into distinct printable page HTML blocks.
 * Sanitizes template ONCE, avoids repeated regex compiling, and separates styles to prevent CSSOM lockup.
 */
export function bulkMergeTemplate(
  templateHtml: string,
  records: Array<Record<string, any>>
): string[] {
  if (!records || records.length === 0) {
    return [templateHtml];
  }

  // Separate style tags from template body so styles aren't duplicated 100 times in memory
  const { styles, body } = separateDocxStylesAndBody(templateHtml);
  const targetBody = body || templateHtml;

  return records.map((record) => {
    let populatedBody = targetBody;
    populatedBody = expandNestedArraysAndTables(populatedBody, record);
    const sanitizedBody = sanitizeDocxPlaceholders(populatedBody);
    const lookup = buildEnrichedLookup(record);
    const placeholderRegex = /\{\{([\s\S]*?)\}\}/g;

    const merged = sanitizedBody.replace(placeholderRegex, (fullMatch, token) => {
      const rawKey = token.trim();
      const norm = normalizeKey(rawKey);
      if (lookup.has(norm)) {
        return lookup.get(norm)!;
      }
      const lower = rawKey.toLowerCase();
      if (lookup.has(lower)) {
        return lookup.get(lower)!;
      }
      if (lookup.has(rawKey)) {
        return lookup.get(rawKey)!;
      }
      return fullMatch;
    });

    return styles ? `${styles}\n${merged}` : merged;
  });
}

/**
 * LocalStorage Custom Template Repository
 */
export function getSavedDocxTemplates(): CustomDocxTemplate[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(TEMPLATES_STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed;
    }
  } catch (e) {
    console.warn('Failed to load saved docx templates', e);
  }
  return [];
}

export function saveDocxTemplate(template: Omit<CustomDocxTemplate, 'createdAt' | 'updatedAt'>): CustomDocxTemplate {
  const existing = getSavedDocxTemplates();
  const now = new Date().toISOString();
  const newTemplate: CustomDocxTemplate = {
    ...template,
    createdAt: now,
    updatedAt: now,
  };

  const filtered = existing.filter((t) => t.id !== template.id);
  const updated = [newTemplate, ...filtered];

  if (typeof window !== 'undefined') {
    try {
      localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(updated));
    } catch (e) {
      console.warn('Failed to save docx template to localStorage', e);
    }
  }

  return newTemplate;
}

export function deleteDocxTemplate(id: string): boolean {
  const existing = getSavedDocxTemplates();
  const updated = existing.filter((t) => t.id !== id);

  if (typeof window !== 'undefined') {
    try {
      localStorage.setItem(TEMPLATES_STORAGE_KEY, JSON.stringify(updated));
      return true;
    } catch (e) {
      console.warn('Failed to delete docx template', e);
    }
  }
  return false;
}

export interface TemplatePlaceholderKey {
  key: string;
  label: string;
  category?: 'student' | 'examination' | 'institution' | 'academic' | 'general' | 'custom' | string;
  sampleValue?: string;
  description?: string;
  isCustom?: boolean;
}

export interface ExtractKeysOptions {
  moduleKeys?: TemplatePlaceholderKey[];
  sampleData?: Record<string, any>;
  columns?: Array<{ id: string; header?: string; label?: string }>;
  metaItems?: Array<{ label: string; value: any }>;
  customKeys?: TemplatePlaceholderKey[];
}

/**
 * Extracts and consolidates all available dynamic placeholder keys strictly based on active context.
 * When moduleKeys are provided by the caller module, it strictly adheres to that schema and enriches with live data.
 * 100% Dynamic & Schema-Driven - Zero hardcoded static fallback arrays.
 */
export function extractAvailableKeysFromContext(
  sampleDataOrOptions?: ExtractKeysOptions | Record<string, any>,
  columns?: Array<{ id: string; header?: string; label?: string }>,
  customKeys?: TemplatePlaceholderKey[],
  moduleKeys?: TemplatePlaceholderKey[],
  metaItems?: Array<{ label: string; value: any }>
): TemplatePlaceholderKey[] {
  const map = new Map<string, TemplatePlaceholderKey>();

  let activeModuleKeys: TemplatePlaceholderKey[] = [];
  let activeSampleData: Record<string, any> | undefined;
  let activeColumns: Array<{ id: string; header?: string; label?: string }> | undefined;
  let activeMetaItems: Array<{ label: string; value: any }> | undefined;
  let activeCustomKeys: TemplatePlaceholderKey[] = [];

  if (sampleDataOrOptions && typeof sampleDataOrOptions === 'object' && 'moduleKeys' in sampleDataOrOptions) {
    // Options object overload
    const opts = sampleDataOrOptions as ExtractKeysOptions;
    activeModuleKeys = opts.moduleKeys || [];
    activeSampleData = opts.sampleData;
    activeColumns = opts.columns;
    activeMetaItems = opts.metaItems;
    activeCustomKeys = opts.customKeys || [];
  } else {
    // Positional parameters overload
    activeSampleData = sampleDataOrOptions as Record<string, any>;
    activeColumns = columns;
    activeCustomKeys = customKeys || [];
    activeModuleKeys = moduleKeys || [];
    activeMetaItems = metaItems;
  }

  // Helper lookup for live sample data enrichment
  const sampleLookup =
    activeSampleData && typeof activeSampleData === 'object'
      ? buildEnrichedLookup(activeSampleData)
      : null;

  // Case A: Module-provided placeholder keys (Strict Curated Schema for the active document)
  if (Array.isArray(activeModuleKeys) && activeModuleKeys.length > 0) {
    activeModuleKeys.forEach((item) => {
      if (item && item.key) {
        const keyId = item.key.toLowerCase().trim();
        let liveVal = item.sampleValue;

        if (sampleLookup) {
          const found =
            sampleLookup.get(keyId) ||
            sampleLookup.get(normalizeKey(keyId)) ||
            sampleLookup.get(item.key);
          if (found !== undefined && found !== null && found !== '[object Object]' && found !== '') {
            liveVal = found;
          }
        }

        map.set(keyId, {
          ...item,
          sampleValue: liveVal,
          category: item.category || 'general',
        });
      }
    });

    // Add user custom keys
    if (Array.isArray(activeCustomKeys)) {
      activeCustomKeys.forEach((ck) => {
        if (ck && ck.key) {
          const keyId = ck.key.toLowerCase().trim();
          let liveVal = ck.sampleValue;
          if (sampleLookup) {
            const found = sampleLookup.get(keyId) || sampleLookup.get(normalizeKey(keyId));
            if (found !== undefined && found !== null && found !== '[object Object]') {
              liveVal = found;
            }
          }
          map.set(keyId, { ...ck, sampleValue: liveVal, category: 'custom', isCustom: true });
        }
      });
    }

    return Array.from(map.values());
  }

  // Case B: Dynamic Fallback when no explicit moduleKeys are provided (Tabular grids / Generic documents)
  if (Array.isArray(activeColumns) && activeColumns.length > 0) {
    activeColumns.forEach((col) => {
      if (!col) return;
      const colId = (col.id || col.header || col.label || '').replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      if (colId && !map.has(colId)) {
        let liveVal = `[${col.label || col.header || col.id}]`;
        if (sampleLookup) {
          const found = sampleLookup.get(colId) || sampleLookup.get(normalizeKey(colId));
          if (found !== undefined && found !== null && found !== '[object Object]') {
            liveVal = found;
          }
        }
        map.set(colId, {
          key: colId,
          label: col.label || col.header || col.id,
          category: 'general',
          sampleValue: liveVal,
          description: `Table column field`,
        });
      }
    });
  } else if (activeSampleData && typeof activeSampleData === 'object') {
    Object.entries(activeSampleData).forEach(([rawKey, val]) => {
      if (val === undefined || val === null || typeof val === 'function') return;
      if (['id', '_id', '__v', 'key', 'children', 'isEditable'].includes(rawKey)) return;
      if (typeof val === 'object' && Array.isArray(val)) return;

      const formattedKey = rawKey.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      const humanLabel = rawKey
        .replace(/([A-Z])/g, ' $1')
        .replace(/[_-]/g, ' ')
        .trim()
        .replace(/^./, (s) => s.toUpperCase());

      map.set(formattedKey, {
        key: formattedKey,
        label: humanLabel,
        category: 'general',
        sampleValue: typeof val === 'object' ? JSON.stringify(val) : String(val),
        description: `Field from document data`,
      });
    });
  }

  // Dynamic extraction from metaItems (e.g. [{ label: 'Class', value: 'Class 10' }])
  if (Array.isArray(activeMetaItems)) {
    activeMetaItems.forEach((meta) => {
      if (!meta || !meta.label) return;
      const metaKey = meta.label.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      if (metaKey && !map.has(metaKey)) {
        map.set(metaKey, {
          key: metaKey,
          label: meta.label,
          category: 'general',
          sampleValue: String(meta.value || ''),
          description: `Document header metadata`,
        });
      }
    });
  }

  // User-defined custom dynamic keys
  if (Array.isArray(activeCustomKeys)) {
    activeCustomKeys.forEach((ck) => {
      if (ck && ck.key) {
        const keyId = ck.key.toLowerCase().trim();
        map.set(keyId, { ...ck, category: 'custom', isCustom: true });
      }
    });
  }

  return Array.from(map.values());
}

