import React from 'react';
import type { LocalizedFieldInput, LocalizedValue } from '@/i18n/localizedEntity';

export interface CustomInputProps {
  id?: string;
  name?: string;
  type?: string;
  value?: string | number | LocalizedFieldInput;
  defaultValue?: string | number | LocalizedFieldInput;
  onChange?: (value: any, event?: any) => void;
  onBlur?: (e: React.FocusEvent<any>) => void;
  onFocus?: (e: React.FocusEvent<any>) => void;
  onKeyDown?: (e: React.KeyboardEvent<any>) => void;
  onEnter?: (e: React.KeyboardEvent<any>) => void;
  onShiftEnter?: (e: React.KeyboardEvent<any>) => void;
  onEmptyBackspace?: (e: React.KeyboardEvent<any>) => void;
  onAdd?: (e: React.KeyboardEvent<any>) => void;
  onAddShift?: (e: React.KeyboardEvent<any>) => void;
  label?: React.ReactNode;
  subLabel?: React.ReactNode;
  required?: boolean;
  optional?: boolean;
  badge?: string;
  placeholder?: string | Record<string, string>;
  size?: 'sm' | 'md' | 'lg';
  variant?: 'default' | 'filled' | 'elevated' | 'sub' | 'borderless' | 'compact-number';
  disabled?: boolean;
  readOnly?: boolean;
  autoFocus?: boolean;
  autoComplete?: string;
  error?: string | null;
  helperText?: string | null;
  success?: boolean;
  showSuccessState?: boolean;
  validate?: (val: string) => string | boolean;
  validateOn?: 'blur' | 'change' | 'both';
  autoSanitize?: boolean;
  clearable?: boolean;
  showPasswordToggle?: boolean;
  showDigitCounter?: boolean;
  showCharCount?: boolean;
  maxLength?: number;
  minLength?: number;
  min?: number;
  max?: number;
  step?: number | string;
  cyclic?: boolean;
  initialScrollValue?: number | string;
  allowDecimals?: boolean;
  allowNegative?: boolean;
  scrollable?: boolean;
  stepper?: boolean;
  currencySymbol?: string;
  prefix?: React.ReactNode;
  suffix?: React.ReactNode;
  unit?: string;
  icon?: React.ComponentType<any> | null;
  startAdornment?: React.ReactNode;
  endAdornment?: React.ReactNode;
  className?: string;
  inputClassName?: string;
  labelClassName?: string;
  wrapperClassName?: string;
  rows?: number;
  autoResize?: boolean;
  inputMode?: 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
  enableTemplates?: boolean;
  templateCategory?: string;
  templateNamespace?: string;
  category?: string;
  namespace?: string;
  templateInitialList?: string[];
  templateMode?: 'append' | 'replace';
  showTemplateClear?: boolean;
  showTemplateSave?: boolean;
  showTemplateSaved?: boolean;
  showTemplateCount?: boolean;
  showTemplateSearch?: boolean;
  templateSearchable?: boolean;
  showTemplateEdit?: boolean;
  templateEditable?: boolean;
  showTemplateDelete?: boolean;
  templateDeletable?: boolean;
  showTemplateOnFocusOnly?: boolean;
  onManage?: (() => void) | null;
  manageLabel?: string | null;
  manageTitle?: string | null;
  onActionClick?: (() => void) | null;
  actionLabel?: string | null;
  actionTo?: string | null;
  actionTitle?: string | null;
  headerAction?: React.ReactNode;
  multiLanguage?: boolean;
  dir?: 'ltr' | 'rtl' | 'auto';
  style?: React.CSSProperties;
  [key: string]: any;
}

declare const CustomInput: React.ForwardRefExoticComponent<
  CustomInputProps & React.RefAttributes<HTMLInputElement | HTMLTextAreaElement>
>;

export default CustomInput;
