/**
 * Institutional ERP Sample Datasets & Production Fixtures
 *
 * Provides complete, realistic, domain-accurate sample datasets for all institutional ERP scenarios:
 * 1. Institution Branding & Campus Metadata
 * 2. Multi-Student Enrolment Rosters (Admit Cards, Desk Slips)
 * 3. Academic Transcript & Examination Marksheet (8+ Subjects, GPA 5.00, Grades)
 * 4. Master Tabulation Ledger (Class Master Ledger with multiple subjects and students)
 * 5. Monthly Tuition & Boarding Fee Slip (Line items, discounts, fines, net payable)
 * 6. Staff Salary & Payroll Slip (Basic, allowances, provident fund, net salary)
 * 7. Character Certificate & Official Testimonial
 * 8. Quran & Hifz Daily Progress Tracker
 * 9. Official Institutional Notice & Circular
 */

import {
  InstitutionData,
  StudentProfileData,
  ExamReportData,
  FeeVoucherData,
  SalarySlipData,
  HifzProgressData,
  InstitutionalNoticeData,
} from './types';

/**
 * 1. Default Institutional Branding
 */
export const SAMPLE_INSTITUTION: InstitutionData = {
  name: 'Jamia Islamia Markazul Uloom',
  nameBangla: 'جامعة اسلامية مركز العلوم',
  nameArabic: 'جامعة إسلامية مركز العلوم',
  shortName: 'JIMU',
  code: 'JIMU-DH-102',
  eiin: '134521',
  logo: '/assets/images/institution-logo.png',
  watermarkLogo: '/assets/images/institution-watermark.png',
  address: 'Plot 14, Block C, Main Road, Uttara, Dhaka-1230, Bangladesh',
  campusName: 'Main Campus',
  branchName: 'Uttara Branch',
  phone: '+880 1812-345678, +880 2-8912345',
  email: 'info@markazululoom.edu.bd',
  website: 'www.markazululoom.edu.bd',
  establishedYear: 1998,
  principalName: 'Mawlana Dr. Muhammad Abul Hasan',
  principalDesignation: 'Principal & Shaykhul Hadith',
  principalSignatureUrl: '/assets/signatures/principal.png',
  examControllerName: 'Mufti Mahmudur Rahman',
  examControllerSignatureUrl: '/assets/signatures/controller.png',
  officialSealUrl: '/assets/seals/official-seal.png',
  tagline: 'Excellence in Islamic Scholarship & Modern Education',
  academicYear: 2026,
  session: '2025-2026',
  currentDate: '2026-09-29',
};

/**
 * 2. Multi-Student Enrolment Roster
 */
export const SAMPLE_STUDENT_ROSTER: StudentProfileData[] = [
  {
    id: 'std_001',
    studentId: 'STD-2026-001',
    name: 'Muhammad Abdullah Al-Amin',
    nameBangla: 'মুহাম্মদ আব্দুল্লাহ আল-আমিন',
    nameArabic: 'محمد عبد الله الأمين',
    rollNumber: 1,
    registrationNumber: 'REG-2026-08101',
    className: 'Class 10 (Dakhil)',
    sectionName: 'A (Abu Bakr)',
    group: 'General',
    shift: 'Morning',
    department: 'Secondary General',
    session: '2025-2026',
    academicYear: 2026,
    gender: 'male',
    dob: '2010-04-15',
    bloodGroup: 'A+',
    photoUrl: '/assets/students/std_001.jpg',
    fatherName: 'Muhammad Abdur Rahim',
    motherName: 'Amina Begum',
    guardianName: 'Muhammad Abdur Rahim',
    guardianPhone: '+880 1711-112233',
    guardianRelation: 'Father',
    address: 'House 22, Road 4, Sector 3, Uttara, Dhaka',
    hallName: 'Imam Bukhari Examination Hall',
    seatNumber: 'H1-A01',
    qrVerificationUrl: 'https://verify.markazululoom.edu.bd/cert/STD-2026-001',
  },
  {
    id: 'std_002',
    studentId: 'STD-2026-002',
    name: 'Ahmad Hasan Farooq',
    nameBangla: 'আহমাদ হাসান ফারুক',
    nameArabic: 'أحمد حسن فاروق',
    rollNumber: 2,
    registrationNumber: 'REG-2026-08102',
    className: 'Class 10 (Dakhil)',
    sectionName: 'A (Abu Bakr)',
    group: 'General',
    shift: 'Morning',
    department: 'Secondary General',
    session: '2025-2026',
    academicYear: 2026,
    gender: 'male',
    dob: '2010-08-20',
    bloodGroup: 'B+',
    photoUrl: '/assets/students/std_002.jpg',
    fatherName: 'Dr. Farooq Ahmad',
    motherName: 'Fatima Khatun',
    guardianName: 'Dr. Farooq Ahmad',
    guardianPhone: '+880 1712-445566',
    guardianRelation: 'Father',
    address: 'House 45, Road 7, Sector 9, Uttara, Dhaka',
    hallName: 'Imam Bukhari Examination Hall',
    seatNumber: 'H1-A02',
    qrVerificationUrl: 'https://verify.markazululoom.edu.bd/cert/STD-2026-002',
  },
  {
    id: 'std_003',
    studentId: 'STD-2026-003',
    name: 'Zubair Bin Tariq',
    nameBangla: 'জুবায়ের বিন তারিক',
    nameArabic: 'زبیر بن طارق',
    rollNumber: 3,
    registrationNumber: 'REG-2026-08103',
    className: 'Class 10 (Dakhil)',
    sectionName: 'A (Abu Bakr)',
    group: 'Science',
    shift: 'Morning',
    department: 'Secondary Science',
    session: '2025-2026',
    academicYear: 2026,
    gender: 'male',
    dob: '2010-11-12',
    bloodGroup: 'O+',
    photoUrl: '/assets/students/std_003.jpg',
    fatherName: 'Tariqul Islam',
    motherName: 'Rabiya Sultana',
    guardianName: 'Tariqul Islam',
    guardianPhone: '+880 1713-778899',
    guardianRelation: 'Father',
    address: 'Sector 11, Uttara, Dhaka',
    hallName: 'Imam Bukhari Examination Hall',
    seatNumber: 'H1-A03',
    qrVerificationUrl: 'https://verify.markazululoom.edu.bd/cert/STD-2026-003',
  },
  {
    id: 'std_004',
    studentId: 'STD-2026-004',
    name: 'Salman Al-Farsi',
    nameBangla: 'সালমান আল-ফারসী',
    nameArabic: 'سلمان الفارسي',
    rollNumber: 4,
    registrationNumber: 'REG-2026-08104',
    className: 'Class 10 (Dakhil)',
    sectionName: 'A (Abu Bakr)',
    group: 'General',
    shift: 'Morning',
    department: 'Secondary General',
    session: '2025-2026',
    academicYear: 2026,
    gender: 'male',
    dob: '2010-02-28',
    bloodGroup: 'AB+',
    photoUrl: '/assets/students/std_004.jpg',
    fatherName: 'Mustafa Kamal',
    motherName: 'Mariam Begum',
    guardianName: 'Mustafa Kamal',
    guardianPhone: '+880 1714-332211',
    guardianRelation: 'Father',
    address: 'Sector 4, Uttara, Dhaka',
    hallName: 'Imam Bukhari Examination Hall',
    seatNumber: 'H1-A04',
    qrVerificationUrl: 'https://verify.markazululoom.edu.bd/cert/STD-2026-004',
  },
];

/**
 * 3. Examination Marksheet & Academic Transcript
 */
export const SAMPLE_EXAM_MARKSHEET: ExamReportData = {
  examId: 'EXAM-2026-ANNUAL-01',
  examName: 'Annual Final Examination 2026',
  examType: 'Summative Assessment',
  academicYear: 2026,
  session: '2025-2026',
  term: 'Final Term',
  publishDate: '2026-09-25',
  student: SAMPLE_STUDENT_ROSTER[0],
  institution: SAMPLE_INSTITUTION,
  subjects: [
    {
      subjectCode: 'QUR-101',
      subjectName: 'Quran Majeed & Tajweed',
      subjectNameBangla: 'কোরআন মাজিদ ও তাজবিদ',
      subjectType: 'compulsory',
      fullMarks: 100,
      cqMarks: 68,
      mcqMarks: 28,
      obtainedMarks: 96,
      highestMarks: 98,
      letterGrade: 'A+',
      gradePoint: 5.0,
      isPassed: true,
      examDate: '2026-09-10',
      teacherRemarks: 'Outstanding memorization and precision in makhraj.',
    },
    {
      subjectCode: 'HAD-102',
      subjectName: 'Hadith Sharif & Usulul Hadith',
      subjectNameBangla: 'হাদিস শরিফ ও উসুলুল হাদিস',
      subjectType: 'compulsory',
      fullMarks: 100,
      cqMarks: 65,
      mcqMarks: 27,
      obtainedMarks: 92,
      highestMarks: 95,
      letterGrade: 'A+',
      gradePoint: 5.0,
      isPassed: true,
      examDate: '2026-09-12',
      teacherRemarks: 'Excellent comprehension of sanad and matn.',
    },
    {
      subjectCode: 'ARB-103',
      subjectName: 'Arabic Language & Literature',
      subjectNameBangla: 'আরবি ভাষা ও সাহিত্য',
      subjectType: 'compulsory',
      fullMarks: 100,
      cqMarks: 62,
      mcqMarks: 26,
      obtainedMarks: 88,
      highestMarks: 94,
      letterGrade: 'A+',
      gradePoint: 5.0,
      isPassed: true,
      examDate: '2026-09-14',
      teacherRemarks: 'Strong grammar and vocabulary mastery.',
    },
    {
      subjectCode: 'FIQ-104',
      subjectName: 'Fiqh & Usulul Fiqh',
      subjectNameBangla: 'ফিকহ ও উসুলুল ফিকহ',
      subjectType: 'compulsory',
      fullMarks: 100,
      cqMarks: 64,
      mcqMarks: 26,
      obtainedMarks: 90,
      highestMarks: 92,
      letterGrade: 'A+',
      gradePoint: 5.0,
      isPassed: true,
      examDate: '2026-09-16',
      teacherRemarks: 'Very clear grasp of juristic principles.',
    },
    {
      subjectCode: 'ENG-105',
      subjectName: 'English Language',
      subjectNameBangla: 'ইংরেজি ভাষা',
      subjectType: 'compulsory',
      fullMarks: 100,
      cqMarks: 58,
      mcqMarks: 25,
      obtainedMarks: 83,
      highestMarks: 89,
      letterGrade: 'A+',
      gradePoint: 5.0,
      isPassed: true,
      examDate: '2026-09-18',
      teacherRemarks: 'Fluent writing and accurate comprehension.',
    },
    {
      subjectCode: 'BNG-106',
      subjectName: 'Bangla Language & Literature',
      subjectNameBangla: 'বাংলা ভাষা ও সাহিত্য',
      subjectType: 'compulsory',
      fullMarks: 100,
      cqMarks: 60,
      mcqMarks: 25,
      obtainedMarks: 85,
      highestMarks: 91,
      letterGrade: 'A+',
      gradePoint: 5.0,
      isPassed: true,
      examDate: '2026-09-20',
      teacherRemarks: 'Creative essays and rich linguistic expression.',
    },
    {
      subjectCode: 'MTH-107',
      subjectName: 'General Mathematics',
      subjectNameBangla: 'সাধারণ গণিত',
      subjectType: 'compulsory',
      fullMarks: 100,
      cqMarks: 67,
      mcqMarks: 30,
      obtainedMarks: 97,
      highestMarks: 100,
      letterGrade: 'A+',
      gradePoint: 5.0,
      isPassed: true,
      examDate: '2026-09-22',
      teacherRemarks: 'Exceptional mathematical problem-solving ability.',
    },
    {
      subjectCode: 'ICT-108',
      subjectName: 'Information & Communication Technology',
      subjectNameBangla: 'তথ্য ও যোগাযোগ প্রযুক্তি',
      subjectType: 'compulsory',
      fullMarks: 50,
      cqMarks: 22,
      mcqMarks: 25,
      obtainedMarks: 47,
      highestMarks: 50,
      letterGrade: 'A+',
      gradePoint: 5.0,
      isPassed: true,
      examDate: '2026-09-24',
      teacherRemarks: 'High digital literacy and practical aptitude.',
    },
  ],
  totalFullMarks: 750,
  totalObtainedMarks: 678,
  averageMarks: 84.75,
  percentage: 90.4,
  gpa: 5.0,
  letterGrade: 'A+',
  meritPosition: 1,
  totalStudentsInClass: 65,
  resultStatus: 'Passed',
  workingDays: 220,
  presentDays: 215,
  absentDays: 5,
  attendancePercentage: 97.7,
  generalRemarks: 'Exemplary academic achievement, disciplined character, and active class participation.',
  gradingScale: [
    { grade: 'A+', gpa: 5.0, minMarks: 80, maxMarks: 100, remarks: 'Outstanding' },
    { grade: 'A', gpa: 4.0, minMarks: 70, maxMarks: 79, remarks: 'Excellent' },
    { grade: 'A-', gpa: 3.5, minMarks: 60, maxMarks: 69, remarks: 'Very Good' },
    { grade: 'B', gpa: 3.0, minMarks: 50, maxMarks: 59, remarks: 'Good' },
    { grade: 'C', gpa: 2.0, minMarks: 40, maxMarks: 49, remarks: 'Satisfactory' },
    { grade: 'D', gpa: 1.0, minMarks: 33, maxMarks: 39, remarks: 'Pass' },
    { grade: 'F', gpa: 0.0, minMarks: 0, maxMarks: 32, remarks: 'Fail' },
  ],
  classTeacherRemarks: 'Abdullah has demonstrated outstanding dedication throughout the academic term.',
  principalRemarks: 'Awarded First Place in Academic Excellence for Class 10.',
};

/**
 * 4. Master Tabulation Ledger Dataset (Multi-Student Class Results)
 */
export const SAMPLE_TABULATION_LEDGER = {
  examName: 'Annual Final Examination 2026',
  className: 'Class 10 (Dakhil)',
  sectionName: 'A (Abu Bakr)',
  session: '2025-2026',
  academicYear: 2026,
  totalStudents: 4,
  institution: SAMPLE_INSTITUTION,
  rows: [
    {
      sl: 1,
      roll: 1,
      studentName: 'Muhammad Abdullah Al-Amin',
      studentId: 'STD-2026-001',
      quran: 96,
      hadith: 92,
      arabic: 88,
      fiqh: 90,
      english: 83,
      bangla: 85,
      math: 97,
      ict: 47,
      totalMarks: 678,
      gpa: 5.0,
      grade: 'A+',
      merit: 1,
      status: 'Passed',
    },
    {
      sl: 2,
      roll: 2,
      studentName: 'Ahmad Hasan Farooq',
      studentId: 'STD-2026-002',
      quran: 90,
      hadith: 88,
      arabic: 84,
      fiqh: 86,
      english: 80,
      bangla: 82,
      math: 91,
      ict: 45,
      totalMarks: 646,
      gpa: 4.88,
      grade: 'A+',
      merit: 2,
      status: 'Passed',
    },
    {
      sl: 3,
      roll: 3,
      studentName: 'Zubair Bin Tariq',
      studentId: 'STD-2026-003',
      quran: 88,
      hadith: 85,
      arabic: 80,
      fiqh: 82,
      english: 78,
      bangla: 80,
      math: 88,
      ict: 44,
      totalMarks: 625,
      gpa: 4.63,
      grade: 'A',
      merit: 3,
      status: 'Passed',
    },
    {
      sl: 4,
      roll: 4,
      studentName: 'Salman Al-Farsi',
      studentId: 'STD-2026-004',
      quran: 82,
      hadith: 79,
      arabic: 75,
      fiqh: 78,
      english: 72,
      bangla: 74,
      math: 80,
      ict: 40,
      totalMarks: 580,
      gpa: 4.13,
      grade: 'A',
      merit: 4,
      status: 'Passed',
    },
  ],
};

/**
 * 5. Monthly Tuition & Boarding Fee Voucher
 */
export const SAMPLE_FEE_VOUCHER: FeeVoucherData = {
  voucherId: 'VCH-2026-09-081',
  voucherNumber: 'INV-2026-09452',
  invoiceDate: '2026-09-01',
  dueDate: '2026-09-15',
  paymentStatus: 'Paid',
  paymentMethod: 'bKash Merchant',
  transactionId: 'TRX-9J82KL091',
  student: SAMPLE_STUDENT_ROSTER[0],
  institution: SAMPLE_INSTITUTION,
  items: [
    {
      sl: 1,
      feeHead: 'Monthly Tuition Fee',
      feeHeadBangla: 'মাসিক টিউশন ফি',
      month: 'September 2026',
      amount: 2500,
      discount: 0,
      fine: 0,
      netAmount: 2500,
      paidAmount: 2500,
      dueAmount: 0,
      status: 'Paid',
    },
    {
      sl: 2,
      feeHead: 'Hostel & Fooding Charges',
      feeHeadBangla: 'হোস্টেল ও খাবার চার্জ',
      month: 'September 2026',
      amount: 4500,
      discount: 500,
      fine: 0,
      netAmount: 4000,
      paidAmount: 4000,
      dueAmount: 0,
      status: 'Paid',
    },
    {
      sl: 3,
      feeHead: 'Examination Fee (Annual)',
      feeHeadBangla: 'বার্ষিক পরীক্ষা ফি',
      month: 'September 2026',
      amount: 800,
      discount: 0,
      fine: 0,
      netAmount: 800,
      paidAmount: 800,
      dueAmount: 0,
      status: 'Paid',
    },
    {
      sl: 4,
      feeHead: 'Library & ICT Lab Fee',
      feeHeadBangla: 'লাইব্রেরি ও আইসিটি ল্যাব ফি',
      month: 'September 2026',
      amount: 300,
      discount: 0,
      fine: 0,
      netAmount: 300,
      paidAmount: 300,
      dueAmount: 0,
      status: 'Paid',
    },
  ],
  subtotal: 8100,
  totalDiscount: 500,
  totalFine: 0,
  grandTotal: 7600,
  paidAmount: 7600,
  dueAmount: 0,
  inWords: 'Seven Thousand Six Hundred Taka Only',
  copyType: 'Student Copy',
  cashierName: 'Kazi Nurul Huda',
  cashierSignatureUrl: '/assets/signatures/cashier.png',
};

/**
 * 6. Staff Salary & Payroll Slip
 */
export const SAMPLE_SALARY_SLIP: SalarySlipData = {
  slipNumber: 'PAY-2026-09-014',
  month: 'September',
  year: 2026,
  paymentDate: '2026-09-30',
  employeeId: 'EMP-1998-005',
  employeeName: 'Mawlana Hafizur Rahman',
  designation: 'Senior Teacher (Arabic & Tajweed)',
  department: 'Department of Quranic Studies',
  joiningDate: '2015-01-01',
  bankName: 'Islami Bank Bangladesh PLC',
  bankAccountNumber: '20501234567890123',
  institution: SAMPLE_INSTITUTION,
  earnings: [
    { id: 'e1', title: 'Basic Salary', category: 'earning', amount: 35000 },
    { id: 'e2', title: 'House Rent Allowance (50%)', category: 'earning', amount: 17500 },
    { id: 'e3', title: 'Medical Allowance', category: 'earning', amount: 3000 },
    { id: 'e4', title: 'Conveyance Allowance', category: 'earning', amount: 2500 },
    { id: 'e5', title: 'Special Academic Allowance', category: 'earning', amount: 2000 },
  ],
  deductions: [
    { id: 'd1', title: 'Provident Fund (10%)', category: 'deduction', amount: 3500 },
    { id: 'd2', title: 'Welfare Fund', category: 'deduction', amount: 500 },
    { id: 'd3', title: 'Income Tax', category: 'deduction', amount: 1200 },
  ],
  basicSalary: 35000,
  grossSalary: 60000,
  totalDeduction: 5200,
  netPayable: 54800,
  netPayableInWords: 'Fifty-Four Thousand Eight Hundred Taka Only',
  paymentStatus: 'Paid',
  preparedBy: 'Accounts Officer',
  approvedBy: 'Principal & Shaykhul Hadith',
};

/**
 * 7. Character Certificate & Testimonial
 */
export const SAMPLE_CERTIFICATE = {
  certificateNumber: 'CERT-2026-0814',
  issueDate: '2026-09-29',
  student: SAMPLE_STUDENT_ROSTER[0],
  institution: SAMPLE_INSTITUTION,
  completionYear: 2026,
  division: 'Distinction (GPA 5.00)',
  moralCharacter: 'Excellent & Exemplary',
  extraCurricular: 'Champion in National Qiraat Competition 2025',
  statementText:
    'This is to certify that Muhammad Abdullah Al-Amin, son of Muhammad Abdur Rahim, was a bonafide student of this institution. During his study, he bore an excellent moral character and actively participated in all academic and spiritual activities. We wish him supreme success in all his future endeavors.',
};

/**
 * 8. Quran & Hifz Daily Progress Tracker
 */
export const SAMPLE_HIFZ_PROGRESS: HifzProgressData = {
  recordDate: '2026-09-29',
  student: SAMPLE_STUDENT_ROSTER[0],
  institution: SAMPLE_INSTITUTION,
  juzNumber: 28,
  currentSurah: 'Surah Al-Mujadila',
  sabaqPages: 'Pages 542 - 544 (3 Pages)',
  sabqiPages: 'Quarter Juz (Juz 28, 1st Quarter)',
  manzilPages: 'Juz 1 to Juz 5 (Full Revision)',
  mistakesCount: 0,
  stuckCount: 1,
  voiceTilaawatQuality: 'Excellent',
  attendanceStatus: 'Present',
  teacherRemarks: 'Flawless memorization today. Recited with complete Tajweed rules.',
};

/**
 * 9. Institutional Notice & Circular
 */
export const SAMPLE_INSTITUTIONAL_NOTICE: InstitutionalNoticeData = {
  noticeNumber: 'NOT-2026-092',
  issueDate: '2026-09-29',
  subject: 'Commencement of Annual Examination 2026 & Exam Hall Guidelines',
  targetAudience: 'All Respected Guardians, Students & Faculty Members',
  bodyText:
    'It is hereby notified for all concerned that the Annual Final Examination 2026 will commence from October 15, 2026. All students must collect their official Admit Cards from the accounts department after clearing all outstanding fee dues by October 10, 2026. Entry into examination halls without official admit cards is strictly prohibited.',
  signedBy: 'Mawlana Dr. Muhammad Abul Hasan',
  designation: 'Principal & Head of Examination Committee',
  referenceNumber: 'JIMU/ADMIN/NOT/2026-092',
  attachmentCount: 1,
  institution: SAMPLE_INSTITUTION,
};
