// Complete Geographic Data for Bangladesh Divisions, Districts, and Major Thanas/Upazilas

export const BANGLADESH_DIVISIONS = [
  'Dhaka',
  'Chattogram',
  'Rajshahi',
  'Khulna',
  'Barishal',
  'Sylhet',
  'Rangpur',
  'Mymensingh',
];

export const BANGLADESH_DISTRICTS_BY_DIVISION = {
  Dhaka: [
    'Dhaka',
    'Gazipur',
    'Narayanganj',
    'Tangail',
    'Faridpur',
    'Manikganj',
    'Munshiganj',
    'Narsingdi',
    'Gopalganj',
    'Madaripur',
    'Rajbari',
    'Shariatpur',
    'Kishoreganj',
  ],
  Chattogram: [
    'Chattogram',
    "Cox's Bazar",
    'Cumilla',
    'Feni',
    'Brahmanbaria',
    'Chandpur',
    'Noakhali',
    'Lakshmipur',
    'Rangamati',
    'Bandarban',
    'Khagrachhari',
  ],
  Rajshahi: [
    'Rajshahi',
    'Bogura',
    'Pabna',
    'Sirajganj',
    'Naogaon',
    'Natore',
    'Chapai Nawabganj',
    'Joypurhat',
  ],
  Khulna: [
    'Khulna',
    'Jashore',
    'Kushtia',
    'Satkhira',
    'Jhenaidah',
    'Chuadanga',
    'Meherpur',
    'Magura',
    'Narail',
    'Bagerhat',
  ],
  Barishal: [
    'Barishal',
    'Bhola',
    'Patuakhali',
    'Pirojpur',
    'Jhalokati',
    'Barguna',
  ],
  Sylhet: [
    'Sylhet',
    'Moulvibazar',
    'Habiganj',
    'Sunamganj',
  ],
  Rangpur: [
    'Rangpur',
    'Dinajpur',
    'Kurigram',
    'Gaibandha',
    'Nilphamari',
    'Lalmonirhat',
    'Thakurgaon',
    'Panchagarh',
  ],
  Mymensingh: [
    'Mymensingh',
    'Jamalpur',
    'Netrokona',
    'Sherpur',
  ],
};

export const MAJOR_THANAS_BY_DISTRICT = {
  Dhaka: [
    'Uttara',
    'Mirpur',
    'Dhanmondi',
    'Gulshan',
    'Banani',
    'Mohammadpur',
    'Badda',
    'Motijheel',
    'Paltan',
    'Tejgaon',
    'Ramna',
    'Jatrabari',
    'Savar',
    'Dhamrai',
    'Keraniganj',
    'Nawabganj',
    'Dohar',
  ],
  Gazipur: ['Gazipur Sadar', 'Kaliakair', 'Kapasia', 'Sreepur', 'Kaliganj', 'Tongi'],
  Narayanganj: ['Narayanganj Sadar', 'Bandar', 'Rupganj', 'Sonargaon', 'Araihazar'],
  Chattogram: ['Kotwali', 'Panchlaish', 'Pahartali', 'Halishahar', 'Agrabad', 'Hathazari', 'Sitakunda', 'Mirsharai', 'Patiya', 'Boalkhali', 'Raozan', 'Fatikchhari'],
  Sylhet: ['Sylhet Sadar', 'Dakshin Surma', 'Beanibazar', 'Golapganj', 'Zakiganj', 'Kanaighat', 'Jaintiapur', 'Gowainghat', 'Companiganj'],
  Rajshahi: ['Boalia', 'Rajpara', 'Motihar', 'Shah Makhdum', 'Paba', 'Godagari', 'Tanore', 'Bagmara', 'Charghat', 'Durgapur', 'Puthia'],
  Khulna: ['Khulna Sadar', 'Sonadanga', 'Khalishpur', 'Daulatpur', 'Khan Jahan Ali', 'Batiaghata', 'Dacope', 'Dumuria', 'Dighalia', 'Koyra', 'Paikgachha', 'Phultala', 'Rupsha', 'Terokhada'],
  Cumilla: ['Cumilla Adarsha Sadar', 'Cumilla Sadar Dakshin', 'Barura', 'Brahmanpara', 'Burichang', 'Chandina', 'Chauddagram', 'Daudkandi', 'Debidwar', 'Homna', 'Laksam', 'Muradnagar', 'Nangalkot', 'Titas', 'Monohargonj'],
  Bogura: ['Bogura Sadar', 'Adamdighi', 'Dhunat', 'Dhupchanchia', 'Gabtali', 'Kahaloo', 'Nandigram', 'Sariakandi', 'Shajahanpur', 'Sherpur', 'Shibganj', 'Sonatala'],
  Mymensingh: ['Mymensingh Sadar', 'Trishal', 'Bhaluka', 'Muktagachha', 'Gafargaon', 'Fulbaria', 'Haluaghat', 'Dhobaura', 'Gouripur', 'Ishwarganj', 'Nandail', 'Tara Khanda'],
};
