/**
 * Notification Sound & Native Device Notification Engine
 * ========================================================
 * 1. App Chime: Soft In-App Web Audio harmonic chime (generated by app).
 * 2. Device Sound: 100% Pure Native OS / System notification (uses OS native notification sound & banner).
 * 3. Mute: Completely silent notifications.
 * 4. User preference persistence across sessions in localStorage.
 */

export type NotificationSoundMode = 'APP_CHIME' | 'DEVICE_SOUND' | 'MUTE';

const SOUND_MODE_KEY = 'spr_notification_sound_mode';
const DEVICE_PREF_KEY = 'spr_notification_device_enabled';

class NotificationSoundEngine {
  private static audioCtx: AudioContext | null = null;

  private static getContext(): AudioContext | null {
    if (typeof window === 'undefined') return null;
    const AudioContextClass = window.AudioContext || (window as any).webkitAudioContext;
    if (!AudioContextClass) return null;

    if (!this.audioCtx || this.audioCtx.state === 'closed') {
      this.audioCtx = new AudioContextClass();
    }
    if (this.audioCtx.state === 'suspended') {
      this.audioCtx.resume().catch(() => {});
    }
    return this.audioCtx;
  }

  /**
   * App Chime Mode: Soft, pleasant harmonic dual-tone chime (E5 -> B5) using Web Audio API.
   */
  public static playAppChime(): void {
    try {
      const ctx = this.getContext();
      if (!ctx) return;
      if (ctx.state === 'suspended') ctx.resume().catch(() => {});

      const now = ctx.currentTime;

      // Primary tone: E5 (659.25 Hz)
      const osc1 = ctx.createOscillator();
      const gain1 = ctx.createGain();
      osc1.type = 'sine';
      osc1.frequency.setValueAtTime(659.25, now);
      gain1.gain.setValueAtTime(0.18, now);
      gain1.gain.exponentialRampToValueAtTime(0.0001, now + 0.38);

      osc1.connect(gain1);
      gain1.connect(ctx.destination);
      osc1.start(now);
      osc1.stop(now + 0.38);

      // Secondary tone: B5 (987.77 Hz) with subtle delay
      const osc2 = ctx.createOscillator();
      const gain2 = ctx.createGain();
      osc2.type = 'sine';
      osc2.frequency.setValueAtTime(987.77, now + 0.12);
      gain2.gain.setValueAtTime(0.22, now + 0.12);
      gain2.gain.exponentialRampToValueAtTime(0.0001, now + 0.58);

      osc2.connect(gain2);
      gain2.connect(ctx.destination);
      osc2.start(now + 0.12);
      osc2.stop(now + 0.58);
    } catch (e) {
      console.warn('[NotificationSoundEngine] App chime playback error:', e);
    }
  }

  public static playChime(): void {
    this.playAppChime();
  }

  public static getSoundMode(): NotificationSoundMode {
    if (typeof window === 'undefined') return 'APP_CHIME';
    const val = localStorage.getItem(SOUND_MODE_KEY);
    if (val === 'DEVICE_SOUND' || val === 'MUTE' || val === 'APP_CHIME') {
      return val;
    }
    const oldBool = localStorage.getItem('spr_notification_sound_enabled');
    if (oldBool === 'false') return 'MUTE';
    return 'APP_CHIME';
  }

  public static setSoundMode(mode: NotificationSoundMode): void {
    if (typeof window === 'undefined') return;
    localStorage.setItem(SOUND_MODE_KEY, mode);
  }
}

/**
 * Native Browser / Device Notification Helpers
 */
export const isDeviceNotificationSupported = (): boolean => {
  return typeof window !== 'undefined' && 'Notification' in window;
};

export const getDeviceNotificationPermission = (): NotificationPermission => {
  if (!isDeviceNotificationSupported()) return 'denied';
  return Notification.permission;
};

export const requestDeviceNotificationPermission = async (): Promise<NotificationPermission> => {
  if (!isDeviceNotificationSupported()) return 'denied';
  try {
    const permission = await Notification.requestPermission();
    if (permission === 'granted') {
      localStorage.setItem(DEVICE_PREF_KEY, 'true');
    }
    return permission;
  } catch (err) {
    console.warn('[Notification] Permission request failed:', err);
    return 'denied';
  }
};

export interface DeviceNotificationOptions {
  body?: string;
  icon?: string;
  actionUrl?: string;
  tag?: string;
  silent?: boolean;
  onClick?: () => void;
}

/**
 * Dispatches a native OS desktop notification with native system alert
 */
export const showDeviceNotification = async (
  title: string,
  options: DeviceNotificationOptions = {}
): Promise<boolean> => {
  if (!isDeviceNotificationSupported()) return false;

  let permission = Notification.permission;
  if (permission === 'default') {
    permission = await requestDeviceNotificationPermission();
  }
  if (permission !== 'granted') {
    console.info('[Notification] Native notification permission not granted:', permission);
    return false;
  }

  const notifOptions: NotificationOptions = {
    body: options.body || '',
    icon: options.icon || '/favicon.svg',
    tag: options.tag || `spr_notif_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    silent: options.silent ?? false,
    data: {
      actionUrl: options.actionUrl || window.location.pathname,
    },
  };

  // Method 1: Modern Chromium ServiceWorker showNotification
  if (typeof navigator !== 'undefined' && 'serviceWorker' in navigator) {
    try {
      const reg = await navigator.serviceWorker.ready;
      if (reg && 'showNotification' in reg) {
        await reg.showNotification(title, notifOptions);
        return true;
      }
    } catch (swErr) {
      console.warn('[Notification] ServiceWorker push dispatch fallback:', swErr);
    }
  }

  // Method 2: Standard Window Notification constructor fallback
  try {
    const notif = new Notification(title, notifOptions);

    notif.onclick = () => {
      window.focus();
      if (options.onClick) {
        options.onClick();
      } else if (options.actionUrl) {
        window.location.href = options.actionUrl;
      }
      notif.close();
    };

    return true;
  } catch (err) {
    console.warn('[Notification] Native push display error:', err);
    return false;
  }
};

/**
 * Unified In-App Alert Trigger (Sound Mode + Native OS Notification)
 */
export const triggerNotificationAlert = async (
  title: string,
  body?: string,
  actionUrl?: string,
  tag?: string
): Promise<void> => {
  const mode = NotificationSoundEngine.getSoundMode();

  if (mode === 'APP_CHIME') {
    // 1. In-App Chime (App sound)
    NotificationSoundEngine.playAppChime();
  } else if (mode === 'DEVICE_SOUND') {
    // 2. 100% Pure Native OS Device Notification (Uses OS notification ringtone, ZERO JS sound)
    await showDeviceNotification(title, {
      body,
      actionUrl,
      tag: tag || `spr_alert_${Date.now()}`,
      silent: false,
    });
  }
  // If mode === 'MUTE', do nothing
};

export const getNotificationSoundMode = (): NotificationSoundMode => {
  return NotificationSoundEngine.getSoundMode();
};

export const setNotificationSoundMode = (mode: NotificationSoundMode): void => {
  NotificationSoundEngine.setSoundMode(mode);
};

export const cycleNotificationSoundMode = (): NotificationSoundMode => {
  const current = getNotificationSoundMode();
  let next: NotificationSoundMode = 'APP_CHIME';
  if (current === 'APP_CHIME') next = 'DEVICE_SOUND';
  else if (current === 'DEVICE_SOUND') next = 'MUTE';
  else next = 'APP_CHIME';

  setNotificationSoundMode(next);
  return next;
};

export const playTestChime = async (mode?: NotificationSoundMode): Promise<void> => {
  const targetMode = mode || NotificationSoundEngine.getSoundMode();
  if (targetMode === 'APP_CHIME') {
    NotificationSoundEngine.playAppChime();
  } else if (targetMode === 'DEVICE_SOUND') {
    // Pure OS Device Notification (Zero synthesized JS audio)
    await showDeviceNotification('SPR Note Notification', {
      body: 'Testing native device notification with OS system sound.',
      tag: `test_device_sound_${Date.now()}`,
      silent: false,
    });
  }
};
