# Generated by Django 6.0.7 on 2026-08-05 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdailyreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
