# Generated by Django 6.0.7 on 2026-08-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useractivitylog_userloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdailyreport',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdailyreport',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdailyreport',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentdailyreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Unprepared', 'Unprepared'), ('Absent', 'Absent')], default='Completed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentdailyreport',
            name='teacher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReportErrorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mistake', 'Mistake'), ('Stuck', 'Stuck')], max_length=10)),
                ('juz', models.IntegerField()),
                ('page', models.IntegerField()),
                ('surah_number', models.IntegerField(blank=True, null=True)),
                ('ayah', models.IntegerField(default=1)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_details', to='core.studentdailyreport')),
            ],
            options={
                'ordering': ['type', 'juz', 'page'],
            },
        ),
        migrations.CreateModel(
            name='ReportPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_juz', models.IntegerField()),
                ('start_page', models.IntegerField()),
                ('start_surah_number', models.IntegerField(blank=True, null=True)),
                ('start_ayah', models.IntegerField(default=1)),
                ('end_juz', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('end_surah_number', models.IntegerField(blank=True, null=True)),
                ('end_ayah', models.IntegerField(default=1)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='core.studentdailyreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
