# Generated by Django 6.0.7 on 2026-08-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_report_portions_and_error_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuckdetail',
            name='report',
        ),
        migrations.DeleteModel(
            name='MistakeDetail',
        ),
        migrations.DeleteModel(
            name='StuckDetail',
        ),
    ]
