# Generated by Django 6.0.7 on 2026-08-09 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_drop_legacy_mistake_stuck_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdailyreport',
            name='total_page',
            field=models.FloatField(default=0.0, help_text='Total pages covered in this session', verbose_name='Total Pages'),
        ),
        migrations.AlterField(
            model_name='studentdailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Server timestamp when report was first generated', verbose_name='Generate Date'),
        ),
        migrations.AlterField(
            model_name='studentdailyreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timezone-adjusted report date/time', verbose_name='Report Date'),
        ),
    ]
