# Generated by Django 6.0.7 on 2026-08-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_total_page_and_verbose_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdailyreport',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='studentdailyreport',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='studentdailyreport',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='studentdailyreport',
            name='is_locked',
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is Edited')),
                ('edit_time', models.DateTimeField(blank=True, help_text='Auto-set when is_edited becomes True', null=True, verbose_name='Edit Time')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Is Locked')),
                ('lock_time', models.DateTimeField(blank=True, help_text='Auto-set when is_locked becomes True', null=True, verbose_name='Lock Time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('delete_time', models.DateTimeField(blank=True, help_text='Auto-set when is_deleted becomes True', null=True, verbose_name='Delete Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_status', to='core.studentdailyreport', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report Status',
                'verbose_name_plural': 'Report Statuses',
            },
        ),
    ]
