# Generated by Django 6.0.7 on 2026-08-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_useractivitylog_user_activitylog_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstatus',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_info', to='core.studentdailyreport', verbose_name='Report'),
        ),
    ]
