# Generated by Django 6.0.7 on 2026-08-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_reportstatus_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='initial_completed_juz',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_bn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
