# Generated by Django 6.0.7 on 2026-08-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_deactivated_at_user_is_deactivated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
