# Generated by Django 6.0.7 on 2026-08-10 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'App Section Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AppSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_globally_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.appsectioncategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global Default'), ('ROLE', 'Role Permission'), ('GROUP', 'Group Permission'), ('USER', 'User Override')], max_length=20)),
                ('target_identifier', models.CharField(max_length=150)),
                ('section_key', models.CharField(max_length=100)),
                ('previous_state', models.BooleanField()),
                ('new_state', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GroupSectionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='core.appsection')),
            ],
            options={
                'unique_together': {('section', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='RoleSectionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin / Nazim'), ('TEACHER', 'Teacher / Ustadh'), ('GUARDIAN', 'Guardian / Parent'), ('STAFF', 'Staff / Accountant')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.appsection')),
            ],
            options={
                'unique_together': {('section', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserSectionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='core.appsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'section')},
            },
        ),
    ]
