# Generated by Django 6.0.7 on 2026-08-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appsectioncategory_appsection_featureflagauditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('hierarchy_level', models.PositiveIntegerField(default=50)),
                ('color_theme', models.CharField(choices=[('emerald', 'Emerald'), ('blue', 'Blue'), ('purple', 'Purple'), ('amber', 'Amber'), ('rose', 'Rose'), ('cyan', 'Cyan')], default='blue', max_length=30)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin / Nazim'), ('TEACHER', 'Teacher / Ustadh'), ('GUARDIAN', 'Guardian / Parent'), ('STAFF', 'Staff / Accountant')], default='TEACHER', max_length=50),
        ),
        migrations.CreateModel(
            name='RoleActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_student', models.BooleanField(default=True)),
                ('can_edit_student', models.BooleanField(default=True)),
                ('can_delete_report', models.BooleanField(default=False)),
                ('can_export_reports', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_permissions', to='core.userrole')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.userrole'),
        ),
    ]
