# Generated by Django 6.0.7 on 2026-08-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_auth_provider_user_google_sub_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='last_active',
            new_name='last_activity',
        ),
        migrations.AddField(
            model_name='usersession',
            name='refresh_token_jti',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(default='Desktop', max_length=50),
        ),
    ]
