# Generated by Django 5.2.17 on 2026-08-14 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_savedmessage_created_by_session_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_mode',
            field=models.CharField(choices=[('QUICK', 'Quick Admission'), ('FULL', 'Full Institutional')], default='QUICK', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='bangla_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id_card_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('PRESENT', 'Present Address'), ('PERMANENT', 'Permanent Address'), ('OFFICE', 'Office/Work Address')], max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('post_office', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('thana_or_upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_permanent_addresses', to='core.address'),
        ),
        migrations.AddField(
            model_name='student',
            name='present_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_present_addresses', to='core.address'),
        ),
        migrations.CreateModel(
            name='StudentAcademicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_year', models.CharField(blank=True, max_length=32, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=32, null=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('previous_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tc_number', models.CharField(blank=True, max_length=64, null=True)),
                ('class_or_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentgroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_academic_details', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_detail', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('NID_CARD', 'Guardian NID'), ('PREVIOUS_MARKSHEET', 'Previous Marksheet'), ('TC', 'Transfer Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='students/documents/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('primary_guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_guardian_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('guardian_relation', models.CharField(default='Father', max_length=64)),
                ('guardian_nid', models.CharField(blank=True, max_length=64, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_guardians', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_detail', to='core.student')),
            ],
        ),
    ]
