# Generated by Django 6.0.7 on 2026-08-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_student_admission_mode_student_bangla_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nid_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicdetail',
            name='previous_school_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
