# Generated by Django 5.2.17 on 2026-08-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_student_nid_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsection',
            name='is_parent',
            field=models.BooleanField(default=False, help_text='True if this is a master category menu'),
        ),
        migrations.AddField(
            model_name='appsection',
            name='parent_key',
            field=models.CharField(blank=True, help_text='Key of parent section', max_length=100, null=True),
        ),
    ]
