# Generated by Django 5.2.17 on 2026-08-15 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_appsection_is_parent_appsection_parent_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleInviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(help_text='e.g. Hifz Teachers Batch 2026', max_length=150)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='0 for unlimited uses')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='core.userrole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
