# Generated by Django 5.2.17 on 2026-08-16 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_academicdepartment_studentclass_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bangla_name', models.CharField(blank=True, default='', max_length=250)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('institution_type', models.CharField(choices=[('MADRASA', 'Madrasa / Maktab'), ('SCHOOL', 'General School'), ('COLLEGE', 'College'), ('COACHING', 'Coaching / Academy'), ('OTHER', 'Other')], default='MADRASA', max_length=50)),
                ('eiin_or_reg_no', models.CharField(blank=True, default='', max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Institution',
                'verbose_name_plural': 'Academic Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='academicdepartment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.academicinstitution'),
        ),
    ]
