# Generated by Django 5.2.17 on 2026-08-16 16:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_backfill_default_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('staff_type', models.CharField(choices=[('TEACHING', 'Teaching Faculty'), ('ADMIN', 'Administrative Staff'), ('SUPPORT', 'Support & Operations'), ('FINANCE', 'Finance & Accounts')], db_index=True, default='TEACHING', max_length=20)),
                ('designation', models.CharField(help_text='e.g. Senior Ustadh, Accountant, Warden', max_length=100)),
                ('employment_status', models.CharField(choices=[('PERMANENT', 'Permanent'), ('PROBATION', 'Probationary'), ('CONTRACT', 'Contractual'), ('TERMINATED', 'Terminated')], default='PERMANENT', max_length=20)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('nid_no', models.CharField(blank=True, default='', max_length=64)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=32)),
                ('blood_group', models.CharField(blank=True, default='', max_length=10)),
                ('salary_type', models.CharField(choices=[('MONTHLY', 'Monthly Fixed'), ('HOURLY', 'Hourly Rate'), ('FIXED', 'Fixed Project/Contract'), ('COMMISSION', 'Commission Based')], default='MONTHLY', max_length=20)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=64)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('mobile_banking_no', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.academicdepartment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.academicinstitution')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['-created_at', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_detail', serialize=False, to='core.staffprofile')),
                ('highest_degree', models.CharField(blank=True, default='', max_length=150)),
                ('specialization', models.CharField(blank=True, default='', help_text='e.g., Hifz, Arabic, Tajweed, Mathematics', max_length=150)),
                ('max_daily_periods', models.PositiveIntegerField(default=6)),
                ('can_review_reports', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralStaffDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duty_title', models.CharField(max_length=150)),
                ('duty_description', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('NORMAL', 'Normal Priority'), ('LOW', 'Low Priority')], default='NORMAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'General Staff Duty',
                'verbose_name_plural': 'General Staff Duties',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Medical / Sick Leave'), ('EMERGENCY', 'Emergency Leave'), ('UNPAID', 'Unpaid Leave')], default='CASUAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_leaves', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'Staff Leave Request',
                'verbose_name_plural': 'Staff Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralStaffDetail',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='general_detail', serialize=False, to='core.staffprofile')),
                ('assigned_zone', models.CharField(blank=True, default='', help_text='e.g., Main Campus, Hostel 1, Admin Block', max_length=150)),
                ('duty_scope', models.TextField(blank=True, default='')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning Shift'), ('EVENING', 'Evening Shift'), ('NIGHT', 'Night Shift'), ('ROTATIONAL', 'Rotational Shift')], default='MORNING', max_length=20)),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late Arrival'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Approved Leave')], db_index=True, default='PRESENT', max_length=20)),
                ('device_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(default='WEB_PORTAL', max_length=64)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance Records',
                'ordering': ['-date', 'staff__employee_id'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'date'), name='unique_staff_daily_attendance')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_class', models.CharField(choices=[('LEAD_TEACHER', 'Lead Teacher / Ustadh'), ('ASSISTANT', 'Assistant Teacher'), ('SUBSTITUTE', 'Substitute Teacher')], default='LEAD_TEACHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.studentclass')),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.studentgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'assigned_class', 'assigned_group', 'session'), name='unique_teacher_class_group_session_assignment')],
            },
        ),
    ]
