# Generated by Django 5.2.17 on 2026-08-16 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_staffprofile_teacherdetail_generalstaffduty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('PUBLIC_HOLIDAY', 'Public / National Holiday'), ('INSTITUTIONAL_HOLIDAY', 'Institutional Holiday'), ('EXAM_PERIOD', 'Examination Period'), ('VACATION', 'Vacation / Semester Break'), ('SPECIAL_EVENT', 'Special Academic Event'), ('TRAINING', 'Faculty / Staff Workshop')], db_index=True, default='INSTITUTIONAL_HOLIDAY', max_length=30)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('affects_students', models.BooleanField(default=True)),
                ('affects_staff', models.BooleanField(default=True)),
                ('is_residential_active', models.BooleanField(default=False, help_text='True if residential madrasa activities continue')),
                ('color_code', models.CharField(default='#38bdf8', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Academic Calendar Event',
                'verbose_name_plural': 'Academic Calendar Events',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekend_days', models.JSONField(blank=True, default=list, help_text="List of weekday names e.g. ['FRIDAY', 'SATURDAY']")),
                ('default_mode', models.CharField(choices=[('DAILY_SINGLE', 'Single Daily Roll Call'), ('MULTI_SESSION', 'Multi-Session Attendance (e.g. Morning / Afternoon)'), ('PERIOD_WISE', 'Period-by-Period Roll Call')], default='DAILY_SINGLE', max_length=20)),
                ('default_late_cutoff_time', models.TimeField(blank=True, null=True)),
                ('auto_excuse_holidays', models.BooleanField(default=True, help_text='Automatically set status to HOLIDAY_EXCUSED on scheduled holidays/weekends')),
                ('auto_notify_absent', models.BooleanField(default=False, help_text='Send automated SMS / App alerts to guardians on unexcused absence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Attendance Policy Setting',
                'verbose_name_plural': 'Attendance Policy Settings',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSessionSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Daily Main, Fajr Sabaq, Period 1, Zuhr Dars', max_length=100)),
                ('slot_type', models.CharField(choices=[('DAILY_GENERAL', 'Full Day General Slot'), ('PERIODIC', 'Periodic Lecture / Class Slot'), ('SESSION_BASED', 'Session Based (Morning / Afternoon / Evening)'), ('RESIDENTIAL_PRAYER', 'Residential / Prayer Sabaq Slot')], default='DAILY_GENERAL', max_length=30)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('late_cutoff_time', models.TimeField(blank=True, null=True)),
                ('order_rank', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_slots', to='core.academicdepartment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_slots', to='core.academicinstitution')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_slots', to='core.studentclass')),
            ],
            options={
                'verbose_name': 'Attendance Session Slot',
                'verbose_name_plural': 'Attendance Session Slots',
                'ordering': ['order_rank', 'start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('category', models.CharField(choices=[('GENERAL', 'General Institutional Task'), ('ACADEMIC', 'Academic & Curriculum'), ('EXAMINATION', 'Examination & Result Prep'), ('ADMINISTRATIVE', 'Administrative & Official'), ('FACILITIES', 'Campus & Facilities')], default='GENERAL', max_length=30)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_institutional_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_institutional_tasks', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_tasks', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Institutional Task',
                'verbose_name_plural': 'Institutional Tasks',
                'ordering': ['is_completed', 'due_date', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late Arrival'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'Approved Leave'), ('HOLIDAY_EXCUSED', 'Holiday / Weekend Excused')], db_index=True, default='PRESENT', max_length=20)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(default='WEB_PORTAL', max_length=64)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendances', to=settings.AUTH_USER_MODEL)),
                ('session_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendances', to='core.attendancesessionslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance Records',
                'ordering': ['-date', 'student__roll_number', 'student__name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'session_slot', 'date'), name='unique_student_slot_date_attendance')],
            },
        ),
    ]
