# Generated by Django 5.2.17 on 2026-08-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_academiccalendarevent_attendancepolicysetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinstitution',
            name='division',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='academicinstitution',
            name='logo_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='academicinstitution',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='academicinstitution',
            name='street_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='academicinstitution',
            name='upazila_thana',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
