# Generated by Django 6.0.7 on 2026-08-17 18:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_academicinstitution_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocHeadcountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_expected', models.IntegerField(default=0)),
                ('total_verified', models.IntegerField(default=0)),
                ('verified_student_ids', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad-Hoc Headcount Session',
                'verbose_name_plural': 'Ad-Hoc Headcount Sessions',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=150)),
                ('device_serial', models.CharField(db_index=True, max_length=100, unique=True)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=4370)),
                ('device_type', models.CharField(choices=[('ZKTECO', 'ZKTeco Push / ADMS Protocol'), ('HIKVISION', 'Hikvision ISAPI / Face Terminal'), ('ANVIZ', 'Anviz Biometric / Cloud'), ('RFID_GATE', 'RFID Gate Scanner'), ('GENERIC_REST', 'Generic REST Webhook Device')], default='ZKTECO', max_length=30)),
                ('location', models.CharField(blank=True, default='Main Gate', max_length=150)),
                ('api_key_or_token', models.CharField(blank=True, default='', max_length=255)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biometric Device',
                'verbose_name_plural': 'Biometric Devices',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPeriodSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_type', models.CharField(choices=[('PERIOD', 'Academic Class Period'), ('SHIFT', 'Shift / General Attendance'), ('SESSION', 'Sabq / Recitation Session'), ('MUTALAA', "Mutala'a / Self Study"), ('BREAK', 'Tiffin / Break')], default='PERIOD', max_length=20)),
                ('period_name', models.CharField(max_length=100)),
                ('period_order', models.IntegerField(default=1)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('late_grace_minutes', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Period Slot',
                'verbose_name_plural': 'Dynamic Period Slots',
                'ordering': ['period_order', 'start_time', 'period_name'],
            },
        ),
        migrations.CreateModel(
            name='GateEntryExitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=150)),
                ('barcode_or_rfid', models.CharField(blank=True, db_index=True, max_length=100)),
                ('punch_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('ENTRY', 'Campus Entry / In'), ('EXIT', 'Campus Exit / Out')], default='ENTRY', max_length=10)),
                ('gate_pass_reason', models.CharField(blank=True, default='', max_length=255)),
                ('device_name', models.CharField(blank=True, default='Main Gate', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gate Entry/Exit Log',
                'verbose_name_plural': 'Gate Entry/Exit Logs',
                'ordering': ['-punch_time'],
            },
        ),
        migrations.CreateModel(
            name='RawAttendancePunchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_pin_or_card', models.CharField(db_index=True, max_length=100)),
                ('punch_timestamp', models.DateTimeField(db_index=True)),
                ('punch_type', models.CharField(choices=[('CHECK_IN', 'Check In / Entry'), ('CHECK_OUT', 'Check Out / Exit'), ('BREAK_OUT', 'Break Out'), ('BREAK_IN', 'Break In')], default='CHECK_IN', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processing_notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raw Attendance Punch Log',
                'verbose_name_plural': 'Raw Attendance Punch Logs',
                'ordering': ['-punch_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPeriodAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present / Conducted'), ('ABSENT', 'Absent'), ('SUBSTITUTED', 'Conducted by Substitute'), ('LEAVE', 'Approved Leave'), ('HOLIDAY', 'Holiday / Weekend')], default='PRESENT', max_length=20)),
                ('is_conducted', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Period Attendance Record',
                'verbose_name_plural': 'Teacher Period Attendance Records',
                'ordering': ['-date', 'teacher__name_en'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRoutineSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_or_kitab_name', models.CharField(max_length=150)),
                ('day_of_week', models.CharField(choices=[('ALL', 'All Active Days'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], default='ALL', max_length=20)),
                ('room_number', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Routine Schedule',
                'verbose_name_plural': 'Teacher Routine Schedules',
                'ordering': ['teacher__name_en', 'period_slot__period_order', 'student_class__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='studentattendance',
            name='unique_student_slot_date_attendance',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='is_bunk_discrepancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_attendances', to='core.studentclass'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_student_attendances', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='taken_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_student_attendances', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='adhocheadcountsession',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_adhoc_headcounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adhocheadcountsession',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_headcounts', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='adhocheadcountsession',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adhoc_headcounts', to='core.studentclass'),
        ),
        migrations.AddField(
            model_name='adhocheadcountsession',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adhoc_headcounts', to='core.studentgroup'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='dynamicperiodslot',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_period_slots', to='core.academicdepartment'),
        ),
        migrations.AddField(
            model_name='dynamicperiodslot',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_period_slots', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='dynamicperiodslot',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_period_slots', to='core.studentclass'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='period_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_period_attendances', to='core.dynamicperiodslot'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'period_slot', 'date'), name='unique_student_period_date_attendance'),
        ),
        migrations.AddField(
            model_name='gateentryexitlog',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_logs', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='gateentryexitlog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_gate_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gateentryexitlog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_logs', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='gateentryexitlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_logs', to='core.student'),
        ),
        migrations.AddField(
            model_name='rawattendancepunchlog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_punches', to='core.biometricdevice'),
        ),
        migrations.AddField(
            model_name='rawattendancepunchlog',
            name='matched_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_biometric_punches', to='core.student'),
        ),
        migrations.AddField(
            model_name='rawattendancepunchlog',
            name='matched_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_biometric_punches', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherperiodattendancerecord',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_period_attendances', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='teacherperiodattendancerecord',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_teacher_period_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherperiodattendancerecord',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_period_attendances', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherperiodattendancerecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_attendances', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherroutineschedule',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_routines', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='teacherroutineschedule',
            name='period_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_routines', to='core.dynamicperiodslot'),
        ),
        migrations.AddField(
            model_name='teacherroutineschedule',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_routines', to='core.studentclass'),
        ),
        migrations.AddField(
            model_name='teacherroutineschedule',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_routines', to='core.studentgroup'),
        ),
        migrations.AddField(
            model_name='teacherroutineschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_schedules', to='core.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherperiodattendancerecord',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.teacherroutineschedule'),
        ),
        migrations.AddConstraint(
            model_name='teacherperiodattendancerecord',
            constraint=models.UniqueConstraint(fields=('schedule', 'date'), name='unique_schedule_date_teacher_attendance'),
        ),
    ]
