# Generated by Django 5.2.17 on 2026-08-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_adhocheadcountsession_biometricdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='salary_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Fixed'), ('MONTHLY_FIXED', 'Monthly Fixed'), ('HOURLY', 'Hourly Rate'), ('FIXED', 'Fixed Project/Contract'), ('COMMISSION', 'Commission Based'), ('PER_PERIOD', 'Per Class / Lecture Period'), ('VOLUNTEER', 'Honorary / Volunteer')], default='MONTHLY', max_length=20),
        ),
    ]
