# Generated by Django 5.2.17 on 2026-08-18 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_staffprofile_salary_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplateConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_CARD', 'Student / Staff ID Card'), ('ADMISSION_SLIP', 'Student Admission Voucher'), ('FEE_VOUCHER', 'Monthly Fee Receipt'), ('TESTIMONIAL_CERTIFICATE', 'Testimonial & Certificate'), ('REPORT_BANNER', 'Report Header Banner')], db_index=True, default='ID_CARD', max_length=40)),
                ('template_name', models.CharField(max_length=150)),
                ('is_default', models.BooleanField(default=False)),
                ('orientation', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=20)),
                ('page_size', models.CharField(choices=[('CR80_PVC', 'CR80 PVC Card (54x85.6mm)'), ('A4', 'A4 Standard'), ('A5', 'A5 Half Page'), ('CUSTOM', 'Custom Size')], default='CR80_PVC', max_length=30)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Document Template Config',
                'verbose_name_plural': 'Document Template Configs',
                'ordering': ['-is_default', 'template_name'],
            },
        ),
    ]
