# Generated by Django 6.0.7 on 2026-08-18 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_academicinstitution_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning / Notice'), ('SUCCESS', 'Success / Verified'), ('ALERT', 'Critical Alert')], default='INFO', max_length=20)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='core.academicinstitution')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'In-App Notification',
                'verbose_name_plural': 'In-App Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App Bell Dropdown'), ('SMS', 'SMS Gateway Provider'), ('WHATSAPP', 'WhatsApp Cloud API'), ('EMAIL', 'SMTP Email Server'), ('PUSH_FCM', 'Firebase Push Notification')], db_index=True, default='SMS', max_length=20)),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('recipient_identifier', models.CharField(max_length=150)),
                ('message_title', models.CharField(blank=True, default='', max_length=200)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SIMULATED', 'Simulated (Dev Mode)')], db_index=True, default='SENT', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_reason', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatch_logs', to='core.academicinstitution')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Dispatch Log',
                'verbose_name_plural': 'Notification Dispatch Logs',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationGatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_type', models.CharField(choices=[('SMS', 'SMS Gateway Provider'), ('WHATSAPP', 'WhatsApp Cloud API'), ('SMTP_EMAIL', 'SMTP Email Server'), ('PUSH_FCM', 'Firebase Push Notification (FCM)')], db_index=True, default='SMS', max_length=20)),
                ('provider_name', models.CharField(choices=[('SSL_WIRELESS', 'SSL Wireless (Bangladesh)'), ('GREENWEB', 'Greenweb SMS Gateway'), ('TWILIO', 'Twilio Global SMS / Messaging'), ('BULK_SMS_BD', 'BulkSMS BD Provider'), ('WHATSAPP_META', 'Meta WhatsApp Business Cloud API'), ('SMTP_CUSTOM', 'Custom SMTP Email Server'), ('GENERIC_REST', 'Custom REST Webhook Gateway')], default='SSL_WIRELESS', max_length=40)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_secret_or_token', models.TextField(blank=True, default='')),
                ('sender_id_or_phone', models.CharField(blank=True, default='', max_length=100)),
                ('api_url', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.IntegerField(blank=True, default=587, null=True)),
                ('use_tls_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('extra_headers_or_params', models.JSONField(blank=True, default=dict)),
                ('balance_cache', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('last_ping_status', models.CharField(blank=True, default='UNTESTED', max_length=50)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_gateways', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Notification Gateway Config',
                'verbose_name_plural': 'Notification Gateway Configs',
                'ordering': ['gateway_type', 'provider_name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('STUDENT_ABSENT', 'Student Absent / Unexcused Alert'), ('STUDENT_LATE', 'Student Late Arrival Alert'), ('GATE_BUNK_ALERT', 'Gate Discrepancy & Bunk Alert'), ('NEW_ADMISSION', 'Student Admission Confirmation Voucher'), ('DAILY_REPORT_SAVED', 'Daily Recitation Progress Report'), ('STAFF_LEAVE_ACTION', 'Staff Leave Desk Notice'), ('GENERAL_BROADCAST', 'General Institutional Announcement'), ('CUSTOM', 'Custom Template')], db_index=True, default='CUSTOM', max_length=40)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('available_tags', models.JSONField(blank=True, default=list)),
                ('is_system_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['-is_system_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTriggerRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('STUDENT_ABSENT', 'Student Absent / Unexcused Alert'), ('STUDENT_LATE', 'Student Late Arrival Alert'), ('GATE_BUNK_ALERT', 'Gate Entry/Exit Discrepancy & Bunk Alert'), ('NEW_ADMISSION', 'Student Admission Confirmation'), ('DAILY_REPORT_SAVED', 'Daily Recitation Report Generated'), ('STAFF_LEAVE_ACTION', 'Staff Leave Applied / Approved'), ('INSTITUTIONAL_ANNOUNCEMENT', 'General Institutional Announcement')], db_index=True, max_length=40)),
                ('channels', models.JSONField(blank=True, default=list, help_text="List of active channels e.g. ['IN_APP', 'SMS', 'WHATSAPP', 'EMAIL']")),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_triggers', to='core.academicinstitution')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_rules', to='core.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification Trigger Rule',
                'verbose_name_plural': 'Notification Trigger Rules',
                'ordering': ['event_type'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'event_type'), name='unique_institution_notification_trigger')],
            },
        ),
    ]
