# Generated by Django 6.0.7 on 2026-08-19 14:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_sync_feature_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution Category',
                'verbose_name_plural': 'Institution Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='generalstaffduty',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='studentacademicdetail',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='studentacademichistory',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
