# Generated by Django 5.2.17 on 2026-08-20 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_institutioncategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=200)),
                ('branch_code', models.CharField(blank=True, default='', max_length=50)),
                ('branch_type', models.CharField(choices=[('MAIN_CAMPUS', 'Main Campus'), ('SUB_BRANCH', 'Sub Branch'), ('FEMALE_BRANCH', 'Female Branch / Mahila Branch'), ('RESIDENTIAL_CAMPUS', 'Residential Campus')], default='MAIN_CAMPUS', max_length=50)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('division', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_charge_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to='core.staffprofile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Academic Branch',
                'verbose_name_plural': 'Academic Branches',
                'ordering': ['branch_name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.academicbranch'),
        ),
        migrations.CreateModel(
            name='ClassPeriodSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=120)),
                ('slot_type', models.CharField(choices=[('TEACHING_PERIOD', 'Teaching Period'), ('BREAK_TIFFIN', 'Break / Tiffin'), ('PRAYER_BREAK', 'Prayer Break'), ('MUTALA_SESSION', 'Mutala / Study Session')], default='TEACHING_PERIOD', max_length=50)),
                ('period_order', models.PositiveIntegerField(default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, default=45)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_slots', to='core.academicbranch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_period_slots', to='core.academicdepartment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_period_slots', to='core.academicinstitution')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_period_slots', to='core.studentclass')),
            ],
            options={
                'verbose_name': 'Class Period Slot',
                'verbose_name_plural': 'Class Period Slots',
                'ordering': ['period_order', 'start_time', 'period_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('GENERAL_SECTION', 'General Section'), ('HIFZ_HALQA', 'Hifz Halqa'), ('RESIDENTIAL_DORM', 'Residential Dorm / Boarding')], default='GENERAL_SECTION', max_length=50)),
                ('room_number', models.CharField(blank=True, default='', max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.academicbranch')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sections', to='core.staffprofile')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.studentclass')),
            ],
            options={
                'verbose_name': 'Class Section',
                'verbose_name_plural': 'Class Sections',
                'ordering': ['student_class', 'section_name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classsection'),
        ),
    ]
