# Generated by Django 5.2.17 on 2026-08-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_sync_feature_registry_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdepartment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.academicbranch'),
        ),
    ]
