# Generated by Django 5.2.17 on 2026-08-24 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_academicdepartment_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(help_text='e.g. Hifz Admission 2026-2027', max_length=150)),
                ('session_year', models.CharField(default='2026-2027', max_length=50)),
                ('max_applications', models.PositiveIntegerField(default=0, help_text='0 for unlimited uses')),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_enroll', models.BooleanField(default=True, help_text='Automatically enroll student upon submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_admission_tokens', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_invite_tokens', to='core.academicinstitution')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_invite_tokens', to='core.studentclass')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_invite_tokens', to='core.studentgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
