# Generated by Django 5.2.17 on 2026-08-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_admissioninvitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicdetail',
            name='previous_class',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicdetail',
            name='previous_study_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
