# Generated by Django 5.2.17 on 2026-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_studentacademicdetail_previous_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicdetail',
            name='previous_passing_year',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicdetail',
            name='previous_result',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicdetail',
            name='previous_roll_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
