# Generated by Django 5.2.17 on 2026-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_studentacademicdetail_previous_passing_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['rank_order', 'employee_id'], 'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='rank_order',
            field=models.IntegerField(db_index=True, default=99, help_text='Institutional hierarchy rank order (1=Principal, 2=VP, etc.)'),
        ),
    ]
