# Generated by Django 5.2.17 on 2026-08-24 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_staffprofile_options_staffprofile_rank_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOnboardingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(help_text='e.g. Senior Faculty Recruitment 2026', max_length=150)),
                ('staff_type', models.CharField(choices=[('TEACHING', 'Teaching Faculty'), ('ADMIN', 'Administrative Staff'), ('SUPPORT', 'Support & Operations'), ('FINANCE', 'Finance & Accounts')], db_index=True, default='TEACHING', max_length=20)),
                ('designation', models.CharField(blank=True, default='', help_text='Preset designation/title', max_length=100)),
                ('rank_order', models.IntegerField(default=99, help_text='Default hierarchy rank')),
                ('max_applications', models.PositiveIntegerField(default=0, help_text='0 for unlimited uses')),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_approve', models.BooleanField(default=True, help_text='Automatically create active StaffProfile upon submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_staff_onboarding_tokens', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_onboarding_tokens', to='core.academicdepartment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_onboarding_tokens', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Staff Onboarding Token',
                'verbose_name_plural': 'Staff Onboarding Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
