# Generated by Django 5.2.17 on 2026-08-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_staffonboardingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffonboardingtoken',
            name='include_payroll',
            field=models.BooleanField(default=False, help_text='Whether to request salary/banking info in public candidate form'),
        ),
    ]
