# Generated by Django 5.2.17 on 2026-08-24 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_staffonboardingtoken_include_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTaxonomySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxonomy_key', models.CharField(db_index=True, help_text='e.g. staff_ranks, working_schedules, event_types, etc.', max_length=64)),
                ('data', models.JSONField(default=list, help_text='List of JSON taxonomy records')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_settings', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Tenant Taxonomy Setting',
                'verbose_name_plural': 'Tenant Taxonomy Settings',
                'unique_together': {('institution', 'taxonomy_key')},
            },
        ),
    ]
