# Generated by Django 5.2.17 on 2026-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_tenanttaxonomysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='admin_edit_window_days',
            field=models.IntegerField(default=30, help_text='Days after attendance date that an Admin can edit any record'),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='class_auto_absent_on_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='class_end_buffer_minutes',
            field=models.IntegerField(default=15, help_text='Minutes after period end before closing'),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='class_late_end_minutes',
            field=models.IntegerField(default=25, help_text='Minutes after period start when LATE window ends (cutoff)'),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='class_late_start_minutes',
            field=models.IntegerField(default=10, help_text='Minutes after period start when LATE status begins'),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='class_teacher_edit_window_hours',
            field=models.IntegerField(default=4, help_text='Hours after period end a regular teacher can edit'),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='residential_auto_absent_on_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='residential_end_buffer_minutes',
            field=models.IntegerField(default=45, help_text='Duration/buffer for checkpoint'),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='residential_late_end_minutes',
            field=models.IntegerField(default=35, help_text='Minutes after checkpoint start when LATE window ends'),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='residential_late_start_minutes',
            field=models.IntegerField(default=15, help_text='Minutes after checkpoint start when LATE begins'),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='residential_teacher_edit_window_hours',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='staff_auto_absent_on_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='staff_end_time',
            field=models.TimeField(blank=True, default='10:00', null=True),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='staff_late_end_time',
            field=models.TimeField(blank=True, default='09:00', null=True),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='staff_late_start_time',
            field=models.TimeField(blank=True, default='08:15', null=True),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='staff_start_time',
            field=models.TimeField(blank=True, default='07:30', null=True),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='staff_teacher_edit_window_hours',
            field=models.IntegerField(default=2),
        ),
    ]
