# Generated by Django 5.2.17 on 2026-08-26 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_attendancepolicysetting_admin_edit_window_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesessionslot',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesessionslot',
            name='effective_from',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='attendancesessionslot',
            name='effective_to',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesessionslot',
            name='history_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='classperiodslot',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classperiodslot',
            name='effective_from',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='classperiodslot',
            name='effective_to',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classperiodslot',
            name='history_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
