# Generated by Django 5.2.17 on 2026-08-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_attendancesessionslot_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicdetail',
            name='previous_average',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicdetail',
            name='previous_grade',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
