# Generated by Django 5.2.17 on 2026-08-27 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_studentacademicdetail_previous_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='effective_from',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, help_text='Date this policy version took active effect', null=True),
        ),
        migrations.AddField(
            model_name='attendancepolicysetting',
            name='history_log',
            field=models.JSONField(blank=True, default=list, help_text='Historical policy snapshots archived over time'),
        ),
    ]
