# Generated by Django 5.2.17 on 2026-08-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_attendancepolicysetting_effective_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.classsection'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='section_type',
            field=models.CharField(choices=[('GENERAL_SECTION', 'General Section'), ('HIFZ_SECTION', 'Quran / Hifz Section'), ('RESIDENTIAL_DORM', 'Residential Dormitory')], default='GENERAL_SECTION', max_length=50),
        ),
    ]
