# Generated by Django 5.2.17 on 2026-08-27 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_studentgroup_section_alter_classsection_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField(default=1)),
                ('room_number', models.CharField(max_length=50)),
                ('room_name', models.CharField(blank=True, default='', max_length=150)),
                ('room_type', models.CharField(choices=[('STUDENT_DORM', 'Student Dormitory'), ('FACULTY_QUARTER', 'Faculty Quarter'), ('GUEST_ROOM', 'Guest Room'), ('STUDY_HALL', 'Study Hall')], default='STUDENT_DORM', max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dormitory_rooms', to='core.academicbranch')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_rooms', to='core.academicinstitution')),
                ('prefect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefect_rooms', to='core.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_rooms', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'Dormitory Room',
                'verbose_name_plural': 'Dormitory Rooms',
                'ordering': ['building__name', 'floor_number', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('OCCUPIED', 'Occupied'), ('VACANT', 'Vacant'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under Maintenance')], default='VACANT', max_length=30)),
                ('assigned_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocations', to='core.staffprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocations', to='core.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core.dormitoryroom')),
            ],
            options={
                'verbose_name': 'Bed Allocation',
                'verbose_name_plural': 'Bed Allocations',
                'ordering': ['room', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='ResidentialBuilding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residential_buildings', to='core.academicbranch')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_buildings', to='core.academicinstitution')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_buildings', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'Residential Building',
                'verbose_name_plural': 'Residential Buildings',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dormitoryroom',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.residentialbuilding'),
        ),
    ]
