# Generated by Django 5.2.17 on 2026-08-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_academicgoal_dailylessonplan_homeworkassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylessonplan',
            name='period_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='dailylessonplan',
            name='period_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_lessons', to='core.classperiodslot'),
        ),
    ]
