# Generated by Django 5.2.17 on 2026-08-28 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_dailylessonplan_period_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylessonplan',
            name='curriculum_book_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailylessonplan',
            name='curriculum_book_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='academicgoal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailylessonplan',
            name='lesson_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='lessonevaluation',
            name='evaluation_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
