# Generated by Django 5.2.17 on 2026-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_dailylessonplan_curriculum_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinstitution',
            name='max_branches',
            field=models.PositiveIntegerField(default=1, help_text='Total allowed branches under this institution'),
        ),
        migrations.AddField(
            model_name='academicinstitution',
            name='max_institutions',
            field=models.PositiveIntegerField(default=1, help_text='Total allowed institutions under this tenant/client'),
        ),
    ]
