# Generated by Django 5.2.17 on 2026-08-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_academicinstitution_max_branches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinstitution',
            name='max_departments',
            field=models.PositiveIntegerField(default=1, help_text='Total allowed departments under this institution'),
        ),
    ]
