# Generated by Django 5.2.17 on 2026-08-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_academicinstitution_max_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='has_sections',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this class supports and manages section divisions'),
        ),
    ]
