# Generated by Django 5.2.17 on 2026-08-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_studentclass_has_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='has_groups',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this class supports and manages group divisions'),
        ),
    ]
