# Generated by Django 5.2.17 on 2026-08-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_studentclass_has_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='has_groups',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this section supports and manages group divisions'),
        ),
    ]
