# Generated by Django 5.2.17 on 2026-08-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_classsection_has_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiodslot',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_period_slots', to='core.classsection'),
        ),
        migrations.AddField(
            model_name='dynamicperiodslot',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_period_slots', to='core.classsection'),
        ),
    ]
