# Generated by Django 5.2.17 on 2026-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_classperiodslot_section_dynamicperiodslot_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmessage',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='report_builder_comments', max_length=100, null=True),
        ),
    ]
