# Generated by Django 5.2.17 on 2026-09-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_savedmessage_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saved Template', 'verbose_name_plural': 'Saved Templates'},
        ),
        migrations.AlterField(
            model_name='savedmessage',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='general', max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='savedmessage',
            table='core_savedmessage',
        ),
    ]
