# Generated by Django 5.2.17 on 2026-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_savedmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdispatchlog',
            name='recipient_identifier',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
