# Generated by Django 5.2.17 on 2026-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_notificationdispatchlog_recipient_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdispatchlog',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In-App Bell Dropdown'), ('SMS', 'SMS Gateway Provider'), ('WHATSAPP', 'WhatsApp Cloud API'), ('EMAIL', 'SMTP Email Server'), ('TELEGRAM', 'Telegram Bot / Channel'), ('PUSH_FCM', 'Firebase Push Notification')], db_index=True, default='SMS', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationgatewayconfig',
            name='gateway_type',
            field=models.CharField(choices=[('SMS', 'SMS Gateway Provider'), ('WHATSAPP', 'WhatsApp Cloud API'), ('SMTP_EMAIL', 'SMTP Email Server'), ('TELEGRAM', 'Telegram Bot / Channel'), ('PUSH_FCM', 'Firebase Push Notification (FCM)')], db_index=True, default='SMS', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationgatewayconfig',
            name='provider_name',
            field=models.CharField(choices=[('SSL_WIRELESS', 'SSL Wireless (Bangladesh)'), ('GREENWEB', 'Greenweb SMS Gateway'), ('TWILIO', 'Twilio Global SMS / Messaging'), ('BULK_SMS_BD', 'BulkSMS BD Provider'), ('WHATSAPP_META', 'Meta WhatsApp Business Cloud API'), ('SMTP_CUSTOM', 'Custom SMTP Email Server'), ('TELEGRAM_BOT', 'Telegram Official Bot API'), ('GENERIC_REST', 'Custom REST Webhook Gateway')], default='SSL_WIRELESS', max_length=40),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employment_status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('PROBATION', 'Probationary'), ('CONTRACT', 'Contractual'), ('VISITING', 'Visiting Faculty'), ('TEMPORARY', 'Temporary'), ('VOLUNTEER', 'Volunteer'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired'), ('TERMINATED', 'Terminated')], default='PERMANENT', max_length=20),
        ),
    ]
