# Generated by Django 5.2.17 on 2026-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_notificationdispatchlog_channel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_class', 'roll_number', 'name_en'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentdailyreport',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Student Daily Report', 'verbose_name_plural': 'Student Daily Reports'},
        ),
        migrations.RemoveConstraint(
            model_name='studentattendance',
            name='unique_student_period_date_attendance',
        ),
        migrations.AddIndex(
            model_name='academiccalendarevent',
            index=models.Index(fields=['institution', 'start_date', 'end_date'], name='idx_cal_inst_dates'),
        ),
        migrations.AddIndex(
            model_name='classsection',
            index=models.Index(fields=['student_class', 'is_deleted'], name='idx_sec_cls_del'),
        ),
        migrations.AddIndex(
            model_name='dailylessonplan',
            index=models.Index(fields=['institution', 'academic_class', 'lesson_date'], name='idx_les_inst_cls_dt'),
        ),
        migrations.AddIndex(
            model_name='gateentryexitlog',
            index=models.Index(fields=['institution', 'punch_time'], name='idx_gate_inst_time'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_rec_read_crt'),
        ),
        migrations.AddIndex(
            model_name='lessonevaluation',
            index=models.Index(fields=['student', 'evaluation_date'], name='idx_eval_stu_dt'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'date'], name='idx_stf_att_dt'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['date', 'status'], name='idx_stf_att_stat'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['institution', 'is_deleted', 'staff_type'], name='idx_stf_inst_del_type'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['institution', 'is_active'], name='idx_stf_inst_active'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution', 'is_deleted'], name='idx_stu_inst_del'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution', 'student_class', 'is_deleted'], name='idx_stu_inst_cls_del'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution', 'status'], name='idx_stu_inst_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution', 'student_id_card_number'], name='idx_stu_inst_card'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'], name='idx_att_stu_date'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student_class', 'date'], name='idx_att_cls_date'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'status'], name='idx_att_dt_stat'),
        ),
        migrations.AddIndex(
            model_name='studentclass',
            index=models.Index(fields=['institution', 'is_deleted'], name='idx_cls_inst_del'),
        ),
        migrations.AddIndex(
            model_name='studentdailyreport',
            index=models.Index(fields=['student', 'date'], name='idx_rep_stu_dt'),
        ),
        migrations.AddIndex(
            model_name='studentdailyreport',
            index=models.Index(fields=['date', 'status'], name='idx_rep_dt_stat'),
        ),
        migrations.AddConstraint(
            model_name='academiccalendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='check_calendar_event_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='bedallocation',
            constraint=models.UniqueConstraint(fields=('room', 'bed_number'), name='unique_dorm_room_bed_number'),
        ),
        migrations.AddConstraint(
            model_name='classperiodslot',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='check_period_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='classsection',
            constraint=models.UniqueConstraint(fields=('student_class', 'section_name'), name='unique_class_section_name'),
        ),
        migrations.AddConstraint(
            model_name='lessonevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('max_score__gt', 0), ('score__lte', models.F('max_score'))), name='check_evaluation_score_range'),
        ),
        migrations.AddConstraint(
            model_name='lessonevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('fluency_rating__gte', 1), ('fluency_rating__lte', 5)), name='check_fluency_rating_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='staffleaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='check_staff_leave_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('student_id_card_number__isnull', False), models.Q(('student_id_card_number', ''), _negated=True)), fields=('institution', 'student_id_card_number'), name='unique_inst_student_card_no'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('period_slot__isnull', False)), fields=('student', 'period_slot', 'date'), name='unique_student_period_date_attendance'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('session_slot__isnull', False)), fields=('student', 'session_slot', 'date'), name='unique_student_session_date_attendance'),
        ),
        migrations.AddConstraint(
            model_name='studentclass',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_inst_class_name'),
        ),
    ]
