# Generated by Django 5.2.17 on 2026-09-14 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('actor_phone', models.CharField(blank=True, default='', max_length=32)),
                ('actor_role', models.CharField(blank=True, default='', max_length=64)),
                ('action', models.CharField(choices=[('CREATE', 'Created Resource'), ('UPDATE', 'Updated Resource'), ('DELETE', 'Deleted Resource'), ('RESTORE', 'Restored Resource'), ('PROMOTE', 'Promoted Student'), ('TRANSFER', 'Transferred Student/Staff'), ('STATUS_CHANGE', 'Status Changed'), ('BULK_MARK', 'Bulk Marked Attendance'), ('EVALUATE', 'Evaluated Sabaq/Lesson'), ('PUBLISH', 'Published Results/Routine'), ('CONFIG_CHANGE', 'Configuration Changed'), ('LOGIN', 'User Logged In'), ('EXPORT', 'Data Exported'), ('IMPORT', 'Data Imported')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(db_index=True, max_length=100)),
                ('resource_name', models.CharField(blank=True, default='', max_length=255)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('changes_summary', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_metadata', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', '-created_at'], name='idx_audit_inst_created'), models.Index(fields=['resource_type', 'resource_id'], name='idx_audit_resource'), models.Index(fields=['actor', '-created_at'], name='idx_audit_actor_created'), models.Index(fields=['action', '-created_at'], name='idx_audit_action_created')],
            },
        ),
    ]
