# Generated by Django 5.2.17 on 2026-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_align_sections_to_correct_tenant_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='academicinstitution',
            name='max_branches',
            field=models.PositiveIntegerField(default=5, help_text='Total allowed branches under this institution'),
        ),
        migrations.AlterField(
            model_name='academicinstitution',
            name='max_departments',
            field=models.PositiveIntegerField(default=10, help_text='Total allowed departments under this institution'),
        ),
    ]
