# Generated by Django 5.2.17 on 2026-10-05 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_student_name_i18n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDocxTemplate',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scope_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('raw_html', models.TextField(blank=True, default='')),
                ('detected_placeholders', models.JSONField(blank=True, default=list)),
                ('is_table_document', models.BooleanField(default=False)),
                ('sample_columns', models.JSONField(blank=True, default=list)),
                ('sample_data', models.JSONField(blank=True, default=list)),
                ('template_type', models.CharField(blank=True, default='template', max_length=50)),
                ('records_count', models.IntegerField(blank=True, default=0)),
                ('source_template_id', models.CharField(blank=True, default='', max_length=128)),
                ('page_properties', models.JSONField(blank=True, default=dict)),
                ('page_size', models.CharField(blank=True, default='A4', max_length=50)),
                ('orientation', models.CharField(blank=True, default='PORTRAIT', max_length=50)),
                ('margin', models.CharField(blank=True, default='NORMAL', max_length=50)),
                ('meta_payload', models.JSONField(blank=True, default=dict)),
                ('is_shared', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_docx_templates', to='core.academicinstitution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_docx_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom DocLab Template',
                'verbose_name_plural': 'Custom DocLab Templates',
                'db_table': 'core_customdocxtemplate',
                'ordering': ['-updated_at'],
            },
        ),
    ]
